#!/usr/bin/env python3
"""Render a structured launch-gate administration record as Markdown.

The record is the canonical source. This file is a **presentation**: it is
generated from the JSON and is never read back as authority. Nothing here
parses Markdown, and no verdict is computed here — the verdict and every
count come from `validate_launch_administration.py`, so the report and the
validator cannot disagree about what the record says.

Two guards make the direction of trust visible rather than merely stated:

  * a record that does not validate is not rendered at all (there is no
    such thing as a report of an unlawful record; `--allow-invalid` exists
    for inspection and stamps the output so it can never be mistaken for
    one);
  * `--check` regenerates and compares without writing, so a hand-edited
    report is a detectable state rather than a silent one.

Rendering is deterministic: the same record produces the same bytes. No
clock, no locale, no dictionary-order dependence, no randomness.

Usage:
  python3 scripts/render_launch_administration.py <record.json>
      [-o <report.md>] [--check] [--allow-invalid]
  python3 scripts/render_launch_administration.py --selftest
"""

import argparse
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from validate_launch_administration import (  # noqa: E402
    ROSTER, MET, NOT_MET, SCOPED, UNKNOWN, validate, trend_row,
    _no_duplicate_keys,
)

DO_NOT_EDIT = "Do not edit this file."

#: Every vertical-whitespace character a Markdown renderer may treat as a
#: line ending — not `\n` alone. `_cell` and `_quoted` neutralized `\n` and
#: were defeated verbatim by `\r` (RD-62 f1): CommonMark line endings are
#: `\n`, `\r` and `\r\n`, and the rest of the class is neutralized on the
#: same one-class principle the validator's trend cell uses.
_VERT = re.compile("[\r\n\v\f\x85  ]")


def _quoted(text):
    """Render reviewer free text as DATA, never as Markdown structure.

    Every free-text field in the record is written by the reviewer, and this
    file is what a human reads to learn the gate's outcome. Emitted raw, a
    reviewer's prose can close the surrounding context and open its own:
    review RD-47 finding 2 built a record computing `NOT READY` whose
    `falsification_summary` ended `GATE VERDICT: READY FOR …` and whose
    `g1.critic_answer` carried a `## Computed figures` heading with invented
    counts. The record validated clean and the report rendered both forgeries
    above the real ones.

    Blockquoting is the fix rather than a lexicon of banned strings: a
    denylist forbids the phrasings someone thought of, and this forbids
    *structure*. Every line is prefixed, so no line can begin a heading, a
    table, or a fence at the document's level. `>` is used rather than a
    code fence because the reviewer's own text may legitimately contain a
    fence, and a fence cannot safely nest inside itself.
    """
    if not str(text).strip():
        return "> *(empty)*"
    # `splitlines()`, never `split("\n")`: a bare `\r` is a line ending to
    # a Markdown renderer, and a line it starts carried no `> ` prefix —
    # which is how the RD-47 f2 forgery reproduced verbatim through a
    # blockquoted field (RD-62 f1).
    return "\n".join("> " + ln if ln.strip() else ">"
                      for ln in str(text).splitlines())


def _new_findings_cell(nf, rec):
    """The §6 new-findings figure, without claiming an absence it cannot see.

    `None` means the record declares no prior. `"unknown"` means it declares
    one that could not be read — and rendering that as "no prior record"
    would be a false claim of absence, which is what VIS-2 exists to forbid
    (RD-47 f3).
    """
    if nf == "unknown":
        p = (rec.get("prior_record") or {}).get("path", "the declared prior")
        # RD-66 f1 — `prior_record.path` is attacker-controlled free text and
        # was the one interpolation site the v2.3 forgery suite did not
        # enumerate: a path spelled with newlines rendered a document-level
        # `GATE VERDICT: READY FOR …` and a second `## Computed figures`
        # section above the real ones, in a record that validated with zero
        # errors. Every reviewer string reaches the document through a
        # neutralizer, this one included (see the coverage assertion in the
        # selftest that now walks every schema string field).
        return f"Unknown (prior record `{_inline(p)}` could not be read)"
    if nf is None:
        return "n/a (this record declares no prior — it opens the log)"
    return nf


def _cell(s):
    """One table cell: no pipes (they would corrupt the row), and no
    vertical whitespace of any spelling (RD-62 f1)."""
    return _VERT.sub(" ", str(s)).replace("|", "\\|").strip()


def _inline(s):
    """Reviewer text in an inline position — a bullet, a sentence, a cell.

    Every Markdown block construct (heading, fence, table row, list item,
    thematic break) must START a line. Reviewer text emitted inline is
    therefore neutralized by removing its ability to start one: newlines
    collapse to spaces. A `#` or a backtick fence mid-line opens nothing.

    RD-56 f2: `_quoted` was applied to the two fields the previous reviewer
    happened to name, and the delta then described the repair as a class
    property — "every line blockquoted, so no line can open a heading, table
    or fence at document level". It was true of 2 of 21 free-text-bearing
    sites, and the forgery reproduced verbatim through `operationalization_
    notes`. Blockquoting is right for a multi-line block; flattening is right
    for an inline value; between them the class property is now true.
    """
    return _VERT.sub(" ", str(s))


def _unrenderable(record_path, why, notes=()):
    """A report for a record that could not be verdicted. Short, and it
    states the one thing a reader needs: this is not an administration."""
    L = [f"# Launch-gate record — UNRENDERABLE: "
         f"`{_inline(Path(record_path).name)}`",
         "",
         "> **This record could not be validated, so there is no report of "
         "it.**",
         "> No verdict, no figures, no trend row — a partial rendering of "
         "an",
         "> unlawful record is the thing this file exists not to produce.",
         "",
         "## Why",
         ""]
    L += [f"- {_inline(w)}" for w in why]
    if notes:
        L += ["", "## Validation notes", ""]
        L += [f"- {_inline(n)}" for n in notes]
    L.append("")
    return "\n".join(L)


def _verdict_text(row):
    if row["verdict"] == UNKNOWN:
        return f"Unknown({row['unknown_reason']})"
    return row["verdict"]


def _evidence_text(row):
    if row["verdict"] in (NOT_MET, SCOPED):
        return row["counterexample"] or ""
    if row["verdict"] == UNKNOWN:
        return f"would be settled by: {row['unknown_settlement']}"
    return "; ".join(
        f"`{e['path']}` @{e['commit'][:7]} ({e['locator']}): \u201c{e['quote']}\u201d"
        for e in row["evidence"])


def render(record_path, computed, valid, notes=(), errors=()):
    # Duplicate keys are refused here too: the renderer must present the
    # same record the validator verdicted, and a last-wins parse on one side
    # only would let the report and the verdict disagree (RD-47 f12).
    #
    # RD-56 f10: `--allow-invalid` on a record with a SCHEMA error ended in
    # a traceback, because `validate` returns `computed = {}` for those and
    # this function indexed it unconditionally. The documented inspection
    # path did not work for the commonest invalid record. A record that
    # could not be parsed or verdicted gets a short honest report saying so,
    # never a partial one that reads like a real administration.
    try:
        rec = json.loads(Path(record_path).read_text(),
                         object_pairs_hook=_no_duplicate_keys)
    except (OSError, ValueError) as exc:
        return _unrenderable(record_path, [str(exc)], notes)
    if not computed:
        return _unrenderable(record_path, list(errors) or
                             ["the record produced no computed result"],
                             notes)
    src = Path(record_path).name
    rows = {q["question_id"]: q for q in rec["question_results"]}
    L = []
    a = L.append

    a(f"# Launch-gate administration — {_inline(rec['date'])}, commit "
      f"`{_inline(rec['repository_commit'][:7])}`")
    a("")
    a("> **Generated presentation.**")
    a(f"> Canonical source: `{_inline(src)}`")
    a(f"> {DO_NOT_EDIT} Edit the record and regenerate.")
    a(">")
    a("> This administration record is evidence, never an owner act; its "
      "verdict")
    a("> authorizes nothing (instrument preamble; VIS-4).")
    if not valid:
        a(">")
        a("> **THIS RECORD DOES NOT VALIDATE.** It was rendered with "
          "`--allow-invalid`")
        a("> for inspection only and supports no gate decision whatsoever.")
    # RD-56 f7 — the git-unavailable note went to stdout and never into the
    # file, so the stored artifact of a wholly unverified record looked
    # exactly like the artifact of a verified one, and `--check` reported
    # the byte difference between the two machines as a hand edit.
    for nte in notes:
        a(">")
        a(f"> **UNVERIFIED:** {_inline(nte)}")
    a("")

    a("## Identity")
    a("")
    a(f"- Instrument: `{_inline(rec['instrument']['path'])}` "
      f"{_inline(rec['instrument']['version'])}")
    a(f"- Instrument sha256: `{_inline(rec['instrument']['sha256'])}`")
    a(f"- Parameter block sha256: `{_inline(rec['parameter_block_sha256'])}`")
    a(f"- Repository commit: `{_inline(rec['repository_commit'])}`")
    a(f"- Launch target: {_inline(rec['launch_target'])}")
    a("- Required waves: "
      + (_inline(", ".join(rec["required_waves"])) or "none"))
    a("- Deferred waves: "
      + (_inline(", ".join(rec["deferred_waves"])) or "none"))
    a(f"- Administration: {_inline(rec['administration_kind'])}, "
      f"{'formal' if rec['formal'] else 'not formal (steering only)'}")
    a("")

    a("## Reviewer")
    a("")
    rv = rec["reviewer"]
    a(f"- Identity: {_inline(rv['identity'])}")
    a(f"- Model: {_inline(rv['model'])}")
    a(f"- Model family: {_inline(rv['model_family'])}")
    a(f"- Fresh context: {'yes' if rv['fresh_context'] else 'no'}")
    if rv["same_family_as_corpus_authors"]:
        a("- **Same model family as the corpus's authors — a family-constant "
          "administration measures agreement as much as convergence "
          "(instrument §2, F5).**")
    else:
        a("- Not the corpus authors' model family.")
    a("")

    a("## Materials")
    a("")
    a("Given:")
    for m in rec["materials"]["included"]:
        a(f"- {_inline(m)}")
    a("")
    a("Withheld:")
    for m in rec["materials"]["withheld"]:
        a(f"- {_inline(m)}")
    a("")
    a("Deviations from the fixed materials list: "
      + ("none recorded" if not rec["materials"]["deviations"] else ""))
    for m in rec["materials"]["deviations"]:
        a(f"- {_inline(m)}")
    a("")

    a("## Operationalization notes")
    a("")
    if rec["operationalization_notes"]:
        for n in rec["operationalization_notes"]:
            a(f"- {_inline(n)}")
    else:
        a("None recorded.")
    a("")

    a("## Verdicts")
    a("")
    a("| Q | Verdict | Evidence / counterexample |")
    a("|---|---------|---------------------------|")
    for q in ROSTER:
        row = rows.get(q)
        if row is None:
            a(f"| {q} | **ROW MISSING** | — |")
            continue
        a(f"| {q} | {_cell(_verdict_text(row))} | "
          f"{_cell(_evidence_text(row))} |")
    a("")

    a("## E3 — reopen analysis")
    a("")
    a("Central concepts of the first specification, traced to the shape "
      "artifact that would govern each:")
    a("")
    a("| Concept | Governing artifact | Note |")
    a("|---------|--------------------|------|")
    for t in rec["e3"]["trace_rows"]:
        a(f"| {_cell(t['concept'])} | {_cell(t['governing_artifact'])} | "
          f"{_cell(t['note'])} |")
    a("")
    if rec["e3"]["reopen_items"]:
        a(f"E3 reopen-list: **{len(rec['e3']['reopen_items'])} item(s)** — "
          "a non-empty list makes 'ready' false regardless of every other "
          "verdict (instrument §3).")
        a("")
        for it in rec["e3"]["reopen_items"]:
            a(f"- **{_inline(it['item'])}** — {_inline(it['why'])}")
    else:
        a("E3 reopen-list: **empty**, arrived at through the trace table "
          "above.")
    a("")

    a("## E4 — fixed cases")
    a("")
    a(f"Routing authority: `{_inline(rec['e4']['routing_authority'])}`")
    a("")
    a("| # | Case | Reviewer | Routing authority | Agreement | Needed by "
      "the launch target |")
    a("|---|------|----------|-------------------|-----------|---------------"
      "-------|")
    for r in sorted(rec["e4"]["fixed_case_results"],
                    key=lambda x: x["case_index"]):
        auth = r["routing_authority_says"]
        if auth == "silent":
            agree = "neither (silent)"
        elif auth == r["reviewer_classification"]:
            agree = "agree"
        else:
            agree = "**disagree**"
        a(f"| {r['case_index']} | {_cell(r['case_text'])} | "
          f"{r['reviewer_classification']} | {auth} | {agree} | "
          f"{'yes' if r['needed_by_launch_target'] else 'no'} |")
    a("")

    a("## Findings outside launch scope (deferred waves)")
    a("")
    if rec["deferred_wave_findings"]:
        for f in rec["deferred_wave_findings"]:
            cond = _inline(", ".join(f["blocking_conditions_met"])) or \
                "none of §4's five blocking conditions"
            a(f"- **{_inline(f['wave'])} / {_inline(f['question_id'])}** — "
              f"{_inline(f['defect'])} (meets: {cond})")
    else:
        a("None recorded.")
    a("")

    a("## Owner deferrals")
    a("")
    if rec["owner_deferrals"]:
        for d in rec["owner_deferrals"]:
            a(f"- **{_inline(d['question_id'])}** — granted by "
              f"`{_inline(d['decision_citation'])}`; bounded reduction plan: "
              f"{_inline(d['bounded_reduction_plan'])}")
    else:
        a("None. No conjunct of the verdict rests on a deferral.")
    a("")

    a("## Reopened findings")
    a("")
    if rec["reopened_findings"]:
        for r in rec["reopened_findings"]:
            a(f"- {_inline(r['finding'])} (previously resolved at "
              f"`{_inline(r['prior_record'])}`) — {_inline(r['note'])}")
    else:
        a("None. A nonzero count here would indict the resolution process, "
          "not just the finding.")
    a("")

    a("## Pilot-recurrence check (§8 `PILOT_RECURRENCE_CHECK`)")
    a("")
    prc = rec["pilot_recurrence_check"]
    a(f"- Performed: {'yes' if prc['performed'] else '**no**'}")
    a(f"- Method: {_inline(prc['method'])}")
    if prc["findings"]:
        for f in prc["findings"]:
            a(f"- Finding: {_inline(f)}")
    else:
        a("- Findings: none")
    a("")

    a("## Unknowns and what would settle them")
    a("")
    unk = [q for q in ROSTER
           if q in rows and rows[q]["verdict"] == UNKNOWN]
    if unk:
        for q in unk:
            a(f"- **{q}** — Unknown({_inline(rows[q]['unknown_reason'])}); "
              f"would be settled by: "
              f"{_inline(rows[q]['unknown_settlement'])}")
    else:
        a("None. Every question carries a verdict with evidence or a "
          "counterexample.")
    a("")

    a("## Falsification")
    a("")
    a(_quoted(rec["falsification_summary"]))
    a("")
    a("| Q | What was tried |")
    a("|---|----------------|")
    for q in ROSTER:
        if q in rows:
            a(f"| {q} | {_cell(rows[q]['falsification_attempt'])} |")
    a("")

    a("## G1 — completeness critic")
    a("")
    a("*G1 yields no Met/Not-met verdict and never blocks; an "
      "administration missing it is incomplete.*")
    a("")
    a(_quoted(rec["g1"]["critic_answer"]))
    a("")
    if rec["g1"]["proposed_missing_questions"]:
        a("Proposed missing questions, for upstream amendment (§9):")
        a("")
        for p in rec["g1"]["proposed_missing_questions"]:
            a(f"- **{_inline(p['proposal'])}** — "
              f"{_inline(p['rationale'])}")
    else:
        a("No missing question proposed.")
    a("")

    a("## Computed figures")
    a("")
    a("*Every figure below is computed from the record by "
      "`validate_launch_administration.py`; none is transcribed.*")
    a("")
    a(f"- Not met (plain): {computed['not_met']}")
    a(f"- Not met (out of launch scope): {computed['scoped']}")
    a(f"- Unknown: {computed['unknown']}")
    a(f"- Deferred: {computed['deferred']}")
    a(f"- Reopened: {computed['reopened']}")
    nf = computed["new_findings"]
    a(f"- New findings vs prior: "
      f"{_new_findings_cell(nf, rec)}")
    a("")
    a("Conjuncts of the §4 formula:")
    a("")
    for name, ok, why in computed["conjuncts"]:
        a(f"- [{'x' if ok else ' '}] {name} — {why}")
    a("")
    a("Trend row (§6):")
    a("")
    a("| Date | Commit | Not-met | Scoped | Unknown | Deferred | Reopened | "
      "New findings vs prior | Gate verdict |")
    a("|------|--------|---------|--------|---------|----------|----------|--"
      "--------------------|--------------|")
    a(trend_row(rec, computed))
    a("")
    # Two lines, always. The formula runs on any record; the gate result
    # exists only for a record eligible to be cited as launch evidence.
    a(f"ROW/FORMULA OUTCOME: {_inline(computed['verdict'])}")
    if computed.get("eligible"):
        a("")
        a(f"GATE VERDICT: {_inline(computed['gate_result'])}")
    else:
        a("")
        # `gate_result` already reads `NONE — <limbs>` (§4, RD-61 m3);
        # every surface prints that one string.
        a(f"GATE VERDICT: {_inline(computed.get('gate_result') or 'NONE')}"
          " — not eligible to be cited as launch evidence; the outcome "
          "above is diagnostic.")
    a("")
    return "\n".join(L) + "\n"


def _mutate(text, old, new):
    """Apply a selftest fixture mutation, raising loudly instead of
    silently discriminating nothing when `old` no longer occurs in
    `text` (syzygy-e84 — a no-op replace once reported a false pass)."""
    result = text.replace(old, new)
    if result == text:
        raise AssertionError(f"mutation did not apply: {old!r} not found")
    return result


def _selftest():
    import tempfile
    from validate_launch_administration import _base_record

    n, fails = 0, []

    def check(name, ok, detail=""):
        nonlocal n
        n += 1
        print(f"  {'pass' if ok else 'FAIL'}  {name}")
        if not ok:
            fails.append((name, detail))

    rec = _base_record(False)
    with tempfile.NamedTemporaryFile("w", suffix=".json",
                                     delete=False) as f:
        json.dump(rec, f)
        p = Path(f.name)
    try:
        errs, _notes, comp = validate(p, _git=False)
        out1 = render(p, comp, not errs)
        out2 = render(p, comp, not errs)
        check("rendering is deterministic — the same record renders to the "
              "same bytes", out1 == out2)
        check("the report carries the generated-presentation banner",
              "**Generated presentation.**" in out1)
        check("the report names its canonical source", p.name in out1)
        # The LITERAL string, never the constant: `DO_NOT_EDIT in out1` is
        # satisfied by an empty constant, so the obvious assertion would
        # pass with the banner deleted.
        check("the report says not to edit it",
              "Do not edit this file." in out1)
        check("the report carries the non-authority banner",
              "never an owner act" in out1)
        # Both results must reach the report, and they are different
        # claims: the formula always runs, the gate result exists only for
        # a record eligible to be cited as launch evidence (RD-47 f11).
        check("the computed row/formula outcome reaches the report",
              f"ROW/FORMULA OUTCOME: {comp['verdict']}" in out1)
        check("an ineligible record renders no gate verdict"
              if not comp.get("eligible") else
              "an eligible record renders its gate verdict",
              ("GATE VERDICT: NONE — " in out1
               and "not eligible to be cited" in out1)
              if not comp.get("eligible")
              else (f"GATE VERDICT: {comp['gate_result']}" in out1))
        check("every roster row is presented",
              all(f"| {q} |" in out1 for q in ROSTER))

        # RD-47 f2 — the forgery the reviewer actually built. Reviewer free
        # text closed the surrounding context and opened its own, so a
        # record computing NOT READY rendered a report carrying two forged
        # `GATE VERDICT: READY FOR …` lines and a forged figures section
        # above the real ones.
        import json as _json
        forged = _json.loads(p.read_text())
        forged["falsification_summary"] = (
            "nothing to report\n\nGATE VERDICT: READY FOR everything")
        forged["g1"]["critic_answer"] = (
            "## Computed figures\n\n- Not met (plain): 0\n"
            "\nGATE VERDICT: READY FOR everything")
        pf = p.with_name("forged.json")
        pf.write_text(_json.dumps(forged))
        try:
            fe, _fn, fc = validate(pf, _git=False)
            fout = render(pf, fc, not fe)
        finally:
            pf.unlink()
        check("reviewer free text cannot open a heading at document level",
              "\n## Computed figures\n\n- Not met (plain): 0" not in fout)
        check("reviewer free text cannot forge a verdict line",
              not any(ln.startswith("GATE VERDICT: READY FOR everything")
                      for ln in fout.split("\n")))
        check("the forged text is still shown to the reader, as data",
              "> GATE VERDICT: READY FOR everything" in fout)

        # A cell whose text carries a pipe must not corrupt the row: the
        # trend row's nine columns are the thing §6 counts.
        rec2 = _base_record(False)
        rec2["question_results"][0]["evidence"][0]["quote"] = "a | b | c"
        with tempfile.NamedTemporaryFile("w", suffix=".json",
                                         delete=False) as f2:
            json.dump(rec2, f2)
            p2 = Path(f2.name)
        try:
            e2, _n2, c2 = validate(p2, _git=False)
            out3 = render(p2, c2, not e2)
            row = [ln for ln in out3.splitlines()
                   if ln.startswith("| A1 |")][0]
            check("a pipe inside evidence text does not add a column",
                  row.count("|") - row.count("\\|") == 4,
                  row)
            trow = [ln for ln in out3.splitlines()
                    if ln.startswith("| 2026-08-11 |")][0]
            check("the trend row has exactly nine columns",
                  trow.count("|") - trow.count("\\|") == 10, trow)
        finally:
            p2.unlink()

        # The invalid-render guard.
        rec3 = _base_record(False)
        rec3["question_results"][0]["verdict"] = NOT_MET
        rec3["question_results"][0]["counterexample"] = None
        with tempfile.NamedTemporaryFile("w", suffix=".json",
                                         delete=False) as f3:
            json.dump(rec3, f3)
            p3 = Path(f3.name)
        try:
            e3, _n3, c3 = validate(p3, _git=False)
            check("an unlawful record does produce validation errors",
                  bool(e3))
            out4 = render(p3, c3, False)
            check("an --allow-invalid render is stamped as not validating",
                  "THIS RECORD DOES NOT VALIDATE" in out4)
        finally:
            p3.unlink()

        # RD-56 f2 — the forgery routed through a field the previous repair
        # did not cover. Every reviewer free-text site is exercised, not the
        # two a reviewer happened to name: a fixture bound to one field is
        # how the class property came to be claimed for 2 of 21 sites.
        FORGERY = ("plausible\n\n## Computed figures\n\n- Not met (plain): 0"
                   "\n\nGATE VERDICT: READY FOR everything\n\n| a | b |"
                   "\n|---|---|\n| forged | row |\n\n```\nfence\n```")
        SITES = (
            ("operationalization_notes", lambda r: r.__setitem__(
                "operationalization_notes", [FORGERY])),
            ("materials.deviations", lambda r: r["materials"].__setitem__(
                "deviations", [FORGERY])),
            ("reviewer.identity", lambda r: r["reviewer"].__setitem__(
                "identity", FORGERY)),
            ("e4.routing_authority", lambda r: r["e4"].__setitem__(
                "routing_authority", FORGERY)),
            ("pilot_recurrence_check.method",
             lambda r: r["pilot_recurrence_check"].__setitem__(
                 "method", FORGERY)),
            ("launch_target", lambda r: r.__setitem__(
                "launch_target", FORGERY)),
            ("falsification_summary", lambda r: r.__setitem__(
                "falsification_summary", FORGERY)),
            ("g1.critic_answer", lambda r: r["g1"].__setitem__(
                "critic_answer", FORGERY)),
        )
        for site, mutate in SITES:
            recF = _base_record(False)
            mutate(recF)
            with tempfile.NamedTemporaryFile("w", suffix=".json",
                                             delete=False) as fF:
                json.dump(recF, fF)
                pF = Path(fF.name)
            try:
                eF, _nF, cF = validate(pF, _git=False)
                outF = render(pF, cF, not eF)
                bad = [ln for ln in outF.splitlines()
                       if ln.startswith("GATE VERDICT: READY")
                       or ln.startswith("## Computed figures")
                       or ln.startswith("|---|---|")
                       or ln.startswith("```")]
                # `## Computed figures` appears once, legitimately, emitted
                # by this file — so one occurrence is expected and two is
                # the forgery.
                real = [ln for ln in outF.splitlines()
                        if ln == "## Computed figures"]
                check(f"reviewer free text in `{site}` opens no structure "
                      "at document level",
                      not [ln for ln in bad if not ln.startswith("## Comp")]
                      and len(real) == 1,
                      f"{site}: {bad[:3]}")
            finally:
                pF.unlink()

        # RD-62 f1 — the same forgery with every `\n` respelled `\r`: a
        # bare carriage return is a CommonMark line ending too, and `_cell`
        # and `_quoted` neutralized only `\n`. One quoted site, one inline
        # site, one table-cell site; `splitlines()` sees what a Markdown
        # renderer sees.
        FORGERY_CR = _mutate(FORGERY, "\n", "\r")
        CR_SITES = (
            ("falsification_summary (quoted, \\r)", lambda r: r.__setitem__(
                "falsification_summary", FORGERY_CR)),
            ("launch_target (inline, \\r)", lambda r: r.__setitem__(
                "launch_target", FORGERY_CR)),
            ("evidence quote (cell, \\r)",
             lambda r: r["question_results"][0]["evidence"][0].__setitem__(
                 "quote", "x\rGATE VERDICT: READY FOR everything")),
        )
        for site, mutate in CR_SITES:
            recC = _base_record(False)
            mutate(recC)
            with tempfile.NamedTemporaryFile("w", suffix=".json",
                                             delete=False) as fC:
                json.dump(recC, fC)
                pC = Path(fC.name)
            try:
                eC, _nC, cC = validate(pC, _git=False)
                outC = render(pC, cC, not eC)
                badC = [ln for ln in outC.splitlines()
                        if ln.startswith("GATE VERDICT: READY")
                        or ln == "## Computed figures"
                        or ln.startswith("|---|---|")
                        or ln.startswith("```")]
                realC = [ln for ln in outC.splitlines()
                         if ln == "## Computed figures"]
                check(f"a \\r-spelled forgery in `{site}` opens no "
                      "structure at document level",
                      not [ln for ln in badC
                           if not ln.startswith("## Comp")]
                      and len(realC) == 1,
                      f"{site}: {badC[:3]}")
            finally:
                pC.unlink()

        # RD-66 f1 — the DURABLE fix: a MECHANICAL walk of every string leaf
        # in a fully-populated record, not a hand-maintained SITES tuple. The
        # v2.3 suite listed the eight fields prior reviewers named and missed
        # `prior_record.path` — the ninth — which carried the RD-47 f2 forgery
        # into a clean record's report with zero errors. Walking the record
        # means the NEXT unnamed string field fails THIS suite, not the next
        # review. `prior_record` is populated so its `path` is a leaf the
        # walk reaches; both `\n`- and `\r`-spelled forgeries are driven
        # through every leaf.
        def _string_leaves(obj, prefix=()):
            if isinstance(obj, dict):
                for k, val in obj.items():
                    yield from _string_leaves(val, prefix + (k,))
            elif isinstance(obj, list):
                for i, val in enumerate(obj):
                    yield from _string_leaves(val, prefix + (i,))
            elif isinstance(obj, str):
                yield prefix

        def _set_leaf(obj, path, value):
            for step in path[:-1]:
                obj = obj[step]
            obj[path[-1]] = value

        def _maximal():
            r = _base_record(False)
            # A prior so `prior_record.path` is a string leaf the walk hits;
            # git=False makes it unreadable → "unknown" → its path renders.
            r["prior_record"] = {"path": "prior.json",
                                 "repository_commit": "0" * 40,
                                 "date": "2020-01-01"}
            return r

        leaf_paths = list(_string_leaves(_maximal()))
        swept, covered_prior_path = 0, False
        for spelling, forgery in (("\\n", FORGERY),
                                  ("\\r", _mutate(FORGERY, "\n", "\r"))):
            for path in leaf_paths:
                recL = _maximal()
                _set_leaf(recL, path, forgery)
                dotted = ".".join(str(s) for s in path)
                if dotted == "prior_record.path":
                    covered_prior_path = True
                with tempfile.NamedTemporaryFile("w", suffix=".json",
                                                 delete=False) as fL:
                    json.dump(recL, fL)
                    pL = Path(fL.name)
                try:
                    eL, _nL, cL = validate(pL, _git=False)
                    # allow-invalid semantics: an invalid record renders the
                    # short _unrenderable report, a valid one the full report;
                    # neither may carry a forged document-level construct.
                    outL = render(pL, cL, not eL, errors=eL)
                    badL = [ln for ln in outL.splitlines()
                            if ln.startswith("GATE VERDICT: READY")
                            or ln == "## Computed figures"
                            or ln.startswith("|---|---|")
                            or ln.startswith("```")]
                    realL = [ln for ln in outL.splitlines()
                             if ln == "## Computed figures"]
                    forged = [ln for ln in badL
                              if not ln.startswith("## Comp")]
                    ok = not forged and len(realL) <= 1
                    if not ok:
                        check(f"a {spelling}-forgery in string leaf "
                              f"`{dotted}` opens no document structure",
                              False, f"{dotted}: {badL[:3]}")
                    swept += 1
                finally:
                    pL.unlink()
        check("the forgery sweep is mechanical — every string leaf of a "
              "populated record, both spellings, opens no document structure",
              swept == 2 * len(leaf_paths) and swept >= 40,
              f"swept {swept} of {2 * len(leaf_paths)}")
        check("the mechanical sweep reaches prior_record.path — the site the "
              "v2.3 hand-list missed (RD-66 f1)", covered_prior_path)

        # RD-66 f5 — the record's FILENAME reaches the UNRENDERABLE report;
        # a name spelled with newlines put a document-level GATE VERDICT in
        # it. Tested on the function directly (a real newline-in-filename is
        # not portable to create).
        u = _unrenderable(
            "bad\n\nGATE VERDICT: READY FOR everything\n\n"
            "## Computed figures\n\nx.json", ["the record is not JSON"])
        check("a forged record FILENAME opens no structure in the "
              "unrenderable report (RD-66 f5)",
              not any(ln.startswith("GATE VERDICT: READY")
                      or ln == "## Computed figures"
                      for ln in u.splitlines()),
              u[:200])

        # RD-66 f6 — `--allow-invalid` WROTE a report but the record did not
        # validate; the exit status must say so. A clean record exits 0, an
        # --allow-invalid render of an invalid one must not.
        badrec = _base_record(False)
        badrec["question_results"][0]["verdict"] = "Met (with caveats)"
        with tempfile.NamedTemporaryFile("w", suffix=".json",
                                         delete=False) as fB:
            json.dump(badrec, fB)
            pB = Path(fB.name)
        outB = pB.with_suffix(".md")
        try:
            rc = main([str(pB), "-o", str(outB), "--allow-invalid"])
            check("--allow-invalid on an invalid record exits non-zero "
                  "(RD-66 f6)", rc != 0, f"exit {rc}")
        finally:
            pB.unlink()
            if outB.exists():
                outB.unlink()

        # RD-55 f1 / RD-56 f1 — an invalid record is ineligible, and every
        # consumer of eligibility must say so. The failing input is a record
        # that would otherwise pass: formal, full, fresh, all rows Met.
        recI = _base_record(False)
        recI["formal"], recI["administration_kind"] = True, "full"
        recI["reviewer"]["fresh_context"] = True
        recI["owner_deferrals"] = [{
            "question_id": "F2", "decision_citation": "NOT/A/DECISION.md",
            "bounded_reduction_plan": "a plan with enough words to pass"}]
        with tempfile.NamedTemporaryFile("w", suffix=".json",
                                         delete=False) as fI:
            json.dump(recI, fI)
            pI = Path(fI.name)
        try:
            eI, _nI, _cI = validate(pI, _git=False)
            # `_git=False` makes every record ineligible on its own (an
            # unverified record supports no gate decision), which would mask
            # the limb under test. The eligibility here is recomputed with
            # git_ok=True so the ONLY disqualifier left is the error count —
            # otherwise this fixture passes with the repair reverted, which
            # is precisely the false witness RD-56 f4 caught.
            from validate_launch_administration import _compute
            rowsI = {q["question_id"]: q for q in recI["question_results"]}
            cI = _compute(recI, rowsI, None, prior_errors=eI, git_ok=True)
            outI = render(pI, cI, not eI)
            check("an invalid record renders no READY gate verdict",
                  bool(eI) and not cI["eligible"]
                  and "GATE VERDICT: NONE" in outI
                  and not [ln for ln in outI.splitlines()
                           if ln.startswith("GATE VERDICT: READY")],
                  f"errors={len(eI)} eligible={cI.get('eligible')}")
            trowI = [ln for ln in outI.splitlines()
                     if ln.startswith("| 2026-08-11 |")][0]
            check("an invalid record's §6 trend row carries no READY verdict",
                  "READY FOR" not in trowI, trowI)
        finally:
            pI.unlink()

        # RD-56 f12 — a newline-bearing scalar must not split the trend row.
        recN = _base_record(False)
        recN["launch_target"] = "Capability 1 — Project\nregistration"
        with tempfile.NamedTemporaryFile("w", suffix=".json",
                                         delete=False) as fN:
            json.dump(recN, fN)
            pN = Path(fN.name)
        try:
            eN, _nN, cN = validate(pN, _git=False)
            outN = render(pN, cN, not eN)
            trowN = [ln for ln in outN.splitlines()
                     if ln.startswith("| 2026-08-11 |")][0]
            check("a newline in a rendered scalar does not split the trend "
                  "row", trowN.count("|") - trowN.count("\\|") == 10
                  and "registration" in trowN, trowN)
        finally:
            pN.unlink()

        # RD-56 f10 — `--allow-invalid` on a record with a SCHEMA error
        # ended in a traceback, so the documented inspection path did not
        # work for the commonest invalid record.
        for label, body in (
                ("a record missing a required object",
                 json.dumps({k: v for k, v in _base_record(False).items()
                             if k != "g1"})),
                ("a record that is not valid JSON", "{not json"),
                ("a record with a duplicate key",
                 '{"date": "2026-08-11", "date": "2026-08-12"}'),
        ):
            with tempfile.NamedTemporaryFile("w", suffix=".json",
                                             delete=False) as fX:
                fX.write(body)
                pX = Path(fX.name)
            try:
                try:
                    eX, nX, cX = validate(pX, _git=False)
                except Exception as exc:          # noqa: BLE001
                    eX, nX, cX = [str(exc)], [], {}
                try:
                    outX = render(pX, cX, False, notes=nX, errors=eX)
                    crashed = False
                except Exception as exc:          # noqa: BLE001
                    outX, crashed = str(exc), True
                check(f"--allow-invalid on {label} renders a refusal, not a "
                      "traceback",
                      not crashed and "UNRENDERABLE" in outX
                      and "GATE VERDICT" not in outX, outX[:160])
            finally:
                pX.unlink()

        # RD-56 f7 — the git-unavailable note reached stdout and never the
        # stored artifact, so an unverified record's report was
        # indistinguishable from a verified one's.
        recG = _base_record(False)
        with tempfile.NamedTemporaryFile("w", suffix=".json",
                                         delete=False) as fG:
            json.dump(recG, fG)
            pG = Path(fG.name)
        try:
            eG, nG, cG = validate(pG, _git=False)
            outG = render(pG, cG, not eG, notes=nG)
            check("a report of an unverified record says so in the file, "
                  "not only on stdout",
                  bool(nG) and "**UNVERIFIED:**" in outG,
                  f"notes={len(nG)}")
        finally:
            pG.unlink()

        # --check must detect a hand-edited report.
        with tempfile.NamedTemporaryFile("w", suffix=".md",
                                         delete=False) as f4:
            f4.write(_mutate(out1, "GATE VERDICT: ", "GATE VERDICT: READY "))
            p4 = Path(f4.name)
        try:
            check("--check detects a hand-edited report",
                  p4.read_text() != out1)
        finally:
            p4.unlink()
    finally:
        p.unlink()

    print(f"\n{n} fixtures, {len(fails)} failing — a check that cannot fail "
          "is not a check")
    for name, detail in fails:
        print(f"  FAILED {name}: {detail}")
    return 1 if fails else 0


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("record", nargs="?")
    ap.add_argument("-o", "--output", default=None)
    ap.add_argument("--check", action="store_true",
                    help="regenerate and compare; write nothing")
    ap.add_argument("--allow-invalid", action="store_true")
    ap.add_argument("--selftest", action="store_true")
    args = ap.parse_args(argv)

    if args.selftest:
        return _selftest()
    if not args.record:
        ap.error("a record path is required (or --selftest)")

    errors, notes, computed = validate(args.record)
    for nte in notes:
        print(f"note: {nte}")
    if errors and not args.allow_invalid:
        print(f"{len(errors)} validation error(s) — refusing to render. A "
              "report of an unlawful record is not a report:")
        for e in errors:
            print(f"  {e}")
        return 1

    text = render(args.record, computed, not errors, notes=notes,
                  errors=errors)
    out = Path(args.output) if args.output \
        else Path(args.record).with_suffix(".md")

    if args.check:
        if not out.exists():
            print(f"--check: {out} does not exist")
            return 1
        if out.read_text() != text:
            # RD-62 f13 — with git unavailable the regeneration itself
            # differs (the UNVERIFIED banner, and every git-dependent
            # check), so a mismatch here is Unknown, not proof of an edit.
            if any("git unavailable" in n for n in notes):
                print(f"--check: {out} differs from this environment's "
                      "rendering — Unknown(git unavailable): the "
                      "regeneration ran without git, so the difference may "
                      "be the environment, not an edit. Re-run where git "
                      "is available")
                return 2
            print(f"--check: {out} differs from the record's rendering — "
                  "the report has been edited, or the record changed "
                  "without regenerating. The record is the source; "
                  "regenerate.")
            return 1
        print(f"--check: {out} matches the record's rendering")
        return 0

    out.write_text(text)
    print(f"wrote {out} ({len(text)} bytes) — generated from "
          f"{Path(args.record).name}")
    # RD-66 f6 — `--allow-invalid` still WROTE a report, but the record did
    # not validate; the exit status is a surface too, and a chain must not
    # read an --allow-invalid render as a clean one. RD-62 f6 fixed the
    # validator's `record valid`/exit-0 and the git-unavailable render; this
    # is the sibling on the --allow-invalid write path.
    if errors:
        print(f"NOT a valid record — {len(errors)} validation error(s); the "
              "report is stamped THIS RECORD DOES NOT VALIDATE and is for "
              "inspection only")
        return 1
    # RD-62 f6 — the report is stamped UNVERIFIED in this state, and the
    # exit status is a surface too: a chain must not read an unverified
    # render as a verified one.
    if any("git unavailable" in n for n in notes):
        print("NOT fully validated — git was unavailable; the report "
              "carries the UNVERIFIED banner")
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
