#!/usr/bin/env python3
"""Validate a **structured** launch-gate administration record and compute
its verdict and trend row.

Scope, stated so nobody mistakes it: this tool validates the record and
computes its derived figures. Readiness semantics are owned by
`launch-gate-pre-specifications.md` (§4); where this tool applies the §4
formula it is checking the record against the instrument, never deciding
readiness independently of it. A record this tool passes can still support
nothing if the instrument's non-mechanical requirements (fresh context,
family disclosure, a genuine falsification attempt) were not honored —
those live in the record's own fields and the reader's judgment.

**Why this tool exists.** Its predecessor, `launch_gate_results.py`, parsed
a human Markdown report as the machine source of a launch decision. Thirteen
consecutive administrations of that instrument returned `REVISE`, and the
findings converged on one question the Markdown could not answer stably:
*is this line the record's own claim, or a quotation of one?* v2.0 removes
the question rather than answering it again. The canonical record is JSON;
the Markdown is generated by `render_launch_administration.py` and is never
parsed back. There is no Markdown or HTML visibility classifier anywhere in
this file's correctness path.

Checks (each with at least one `--selftest` mutation fixture):

  LA-1  schema conformance against the committed JSON Schema — types, the
        closed verdict vocabulary, required fields, and `additionalProperties:
        false` everywhere, so an unknown key is an error rather than a
        silently ignored one. A `final_verdict` key is rejected here: the
        verdict is computed, and a record that cannot claim one cannot be
        believed about one
  LA-2  identity — the named commit exists; the instrument is committed at
        it; the record's instrument sha256 matches those bytes; the
        parameter-block sha256 matches §8 of those bytes; the declared
        instrument version matches the committed `effective_version`
  LA-3  binding — the record's launch target equals (whitespace-normalized)
        the parameter block's `LAUNCH_TARGET` or its first sentence, and the
        required/deferred wave lists equal the parameter block's
  LA-4  roster — exactly the full question set is answered, once each:
        A1–A6, B1–B5, C1–C7, D1–D4, E1 with its five sub-rows, E2–E6,
        F1–F6. A missing row is an error, never a pass; an extra row is an
        error too, so an invented question cannot enter the computed columns
  LA-5  verdict/scope agreement — `launch_scope: deferred-wave-only` is
        lawful with the scoped verdict and with no other, and the scoped
        verdict only in A–D. The two fields are authored independently and
        cross-checked, so one typo cannot launder a defect out of scope
  LA-6  evidence discipline — `Met` requires at least one evidence entry;
        either `Not met` form requires a counterexample; `Unknown` requires
        both a reason and what would settle it; fields that do not belong to
        the verdict must be null; and every evidence entry is anchored to
        the record's own `repository_commit`
  LA-7  E1 rolls up — `E1` is `Met` only when all five sub-rows are `Met`
  LA-8  scoped rows are disclosed — any scoped row requires a
        `deferred_wave_findings` entry naming that question, and a finding
        that meets any of §4's five blocking conditions cannot support a
        scoped verdict
  LA-9  E3's credibility protocol — `Met` requires the concept enumeration
        and a trace row per concept; a non-empty reopen list forbids `E3 |
        Met` and forbids any READY verdict (§3's self-declared sharpest
        single gate)
  LA-10 E4's fixed cases — one result per `E4_CASES` case, indices exactly
        1..n, each `case_text` equal to the instrument's own case text, so a
        paraphrased case cannot carry a verdict; reviewer/authority
        disagreement forbids `E4 | Met`; and silence over a case the launch
        target needs routed must be recorded in the operationalization notes
  LA-11 deferrals are cited, not asserted — each names a repository path
        that exists at the named commit and is a file, or an `SDR-n` that
        exists in the decisions home; `P-n` (the queue of decisions *not*
        made), `D-n` (a delta item) and `B-n` (review-finding numbering)
        grant nothing; and no deferral may be claimed against a conjunct §4
        calls never deferrable
  LA-12 the §4 formula, computed — both pass branches run the full conjunct
        battery: every E row `Met`, no plain `Not met` in launch-scope A–D,
        F1 `Met`-or-`Unknown`, F3 `Met`, F4 `Met`. Plain `READY FOR`
        additionally requires F2 `Met` and zero deferrals;
        `READY-WITH-DEFERRALS` substitutes exactly the F2 limb with an
        owner-cited deferral and requires a nonzero deferral count
  LA-13 administration integrity — a `formal` administration must be
        `full`, must be fresh-context, and a `delta` record can never
        support a gate decision (§2)
  LA-14 G1 — present, answered, and never a verdict row. The roster (LA-4)
        already refuses a `G1` row; this check refuses a placeholder answer,
        because a G1 section that says "none" is the absence LA-4 would have
        caught wearing the shape of a presence
  LA-15 trend anchoring — a declared prior record must exist, its commit
        must be an ancestor of this record's commit, and its date must not
        follow this one; a `--prior` file must be the record `prior_record`
        names
  LA-16 the pilot-recurrence check (§8 `PILOT_RECURRENCE_CHECK`) is
        performed and its method recorded, on any formal administration
        that opens the trend log

Every free-text field this tool relies on is checked against a placeholder
lexicon: a value whose tokens are all placeholders ("none", "n/a", "tbd")
asserts emptiness, and asserting emptiness is not answering. Presence tests
elsewhere are content-blind by design — the truthfulness of an evidence
quote stays with the reader.

Usage:
  python3 scripts/validate_launch_administration.py <record.json>
      [--schema launch-gate-administration.schema.json]
      [--prior <record.json>] [--trend-row]
  python3 scripts/validate_launch_administration.py --selftest
"""

import argparse
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DEFAULT_SCHEMA = REPO / "launch-gate-administration.schema.json"
DECISIONS_HOME = ".syzygy/governance/decisions"

# --------------------------------------------------------------------------
# The question roster. Order is presentation order; membership is the check.
# --------------------------------------------------------------------------
ROSTER = (
    [f"A{i}" for i in range(1, 7)]
    + [f"B{i}" for i in range(1, 6)]
    + [f"C{i}" for i in range(1, 8)]
    + [f"D{i}" for i in range(1, 5)]
    + ["E1-form", "E1-home", "E1-granularity", "E1-acceptance-authority",
       "E1-change-process", "E1"]
    + [f"E{i}" for i in range(2, 7)]
    + [f"F{i}" for i in range(1, 7)]
)
ROSTER_SET = frozenset(ROSTER)
E1_SUBROWS = ("E1-form", "E1-home", "E1-granularity",
              "E1-acceptance-authority", "E1-change-process")
E_ROWS = tuple(q for q in ROSTER if q.startswith("E"))
AD_ROWS = tuple(q for q in ROSTER if q[0] in "ABCD")

MET = "Met"
NOT_MET = "Not met"
SCOPED = "Not met (out of launch scope)"
UNKNOWN = "Unknown"

# §4: the conjuncts that carry their own rationale for blocking are never
# deferrable. Only F2 has a deferral limb.
NEVER_DEFERRABLE = frozenset(E_ROWS) | frozenset(AD_ROWS) | {"F1", "F3", "F4"}

# RD35-05's lexicon, carried forward: a value built only of these tokens
# asserts emptiness rather than answering.
_PLACEHOLDER_TOKENS = frozenset((
    "none", "no", "nothing", "nil", "n/a", "na", "tbd", "tba", "todo",
    "unknown", "unspecified", "pending", "-", "--", "—", "(none)", "()",
    "empty", "not", "applicable", "yet", "identified", "found", "known",
))


def _is_placeholder(value: str) -> bool:
    """True when every token falls inside the placeholder lexicon."""
    toks = [t.strip("()[[]].,;:\"'*_`") for t in str(value).lower().split()]
    toks = [t for t in toks if t]
    return not toks or all(t in _PLACEHOLDER_TOKENS for t in toks)


# ==========================================================================
# A deliberately small JSON Schema subset interpreter.
#
# The alternative — re-stating the schema's rules in Python beside the
# committed schema — is the defect RD45-06 named: expectations derived from
# the thing under test. Here the committed schema IS the rule and this code
# only interprets it. The safety property that makes that honest is
# `_audit_schema`: any keyword this interpreter does not implement is a hard
# error when it appears in the schema, so the schema can never quietly rely
# on a keyword that is being ignored.
# ==========================================================================
_SUPPORTED_KEYWORDS = frozenset((
    "$schema", "$id", "title", "description",          # annotations
    "type", "enum", "const", "pattern", "minLength",
    "properties", "required", "additionalProperties",
    "items", "minItems", "uniqueItems",
    "oneOf", "$ref", "$defs",
))
_SCHEMA_VALUED = frozenset(("items",))
_SCHEMA_MAP_VALUED = frozenset(("properties", "$defs"))
_SCHEMA_LIST_VALUED = frozenset(("oneOf",))

_TYPES = {
    "object": lambda v: isinstance(v, dict),
    "array": lambda v: isinstance(v, list),
    "string": lambda v: isinstance(v, str),
    "boolean": lambda v: isinstance(v, bool),
    "null": lambda v: v is None,
    "integer": lambda v: isinstance(v, int) and not isinstance(v, bool),
    "number": lambda v: isinstance(v, (int, float)) and not isinstance(v, bool),
}


def _audit_schema(node, path, out):
    """Reject any keyword the interpreter does not implement."""
    if not isinstance(node, dict):
        out.append(f"{path}: schema node is not an object")
        return
    for k, v in node.items():
        here = f"{path}/{k}"
        if k not in _SUPPORTED_KEYWORDS:
            out.append(f"{here}: unsupported schema keyword {k!r} — this "
                       "validator implements a documented subset, and an "
                       "unimplemented keyword would be silently ignored")
            continue
        if k == "additionalProperties" and v is not False:
            out.append(f"{here}: only `additionalProperties: false` is "
                       "implemented")
        elif k in _SCHEMA_MAP_VALUED:
            if not isinstance(v, dict):
                out.append(f"{here}: expected an object of schemas")
                continue
            for name, sub in v.items():
                _audit_schema(sub, f"{here}/{name}", out)
        elif k in _SCHEMA_VALUED:
            _audit_schema(v, here, out)
        elif k in _SCHEMA_LIST_VALUED:
            if not isinstance(v, list):
                out.append(f"{here}: expected a list of schemas")
                continue
            for i, sub in enumerate(v):
                _audit_schema(sub, f"{here}/{i}", out)


def _resolve(ref, root):
    if not ref.startswith("#/"):
        raise ValueError(f"only local refs are implemented, got {ref!r}")
    node = root
    for part in ref[2:].split("/"):
        node = node[part]
    return node


def _instance_errors(inst, sch, root, path, out):
    """Validate `inst` against `sch`. Appends human-readable errors."""
    if "$ref" in sch:
        _instance_errors(inst, _resolve(sch["$ref"], root), root, path, out)
        return

    if "oneOf" in sch:
        hits = 0
        for sub in sch["oneOf"]:
            probe = []
            _instance_errors(inst, sub, root, path, probe)
            if not probe:
                hits += 1
        if hits != 1:
            out.append(f"{path}: matches {hits} of the oneOf branches, "
                       "exactly one is required")
            return

    if "const" in sch and inst != sch["const"]:
        out.append(f"{path}: expected the constant {sch['const']!r}, "
                   f"found {inst!r}")
        return

    if "enum" in sch and inst not in sch["enum"]:
        out.append(f"{path}: {inst!r} is outside the closed set "
                   f"{sch['enum']!r}")
        return

    if "type" in sch:
        t = sch["type"]
        if not _TYPES[t](inst):
            out.append(f"{path}: expected {t}, found "
                       f"{type(inst).__name__}")
            return

    if isinstance(inst, str):
        if "minLength" in sch and len(inst) < sch["minLength"]:
            out.append(f"{path}: shorter than the required "
                       f"{sch['minLength']} character(s)")
        if "pattern" in sch and not re.search(sch["pattern"], inst):
            out.append(f"{path}: {inst!r} does not match "
                       f"/{sch['pattern']}/")

    if isinstance(inst, list):
        if "minItems" in sch and len(inst) < sch["minItems"]:
            out.append(f"{path}: {len(inst)} item(s), at least "
                       f"{sch['minItems']} required")
        if sch.get("uniqueItems") and len(inst) != len(
                {json.dumps(x, sort_keys=True) for x in inst}):
            out.append(f"{path}: items are not unique")
        if "items" in sch:
            for i, el in enumerate(inst):
                _instance_errors(el, sch["items"], root, f"{path}[{i}]", out)

    if isinstance(inst, dict):
        for req in sch.get("required", []):
            if req not in inst:
                out.append(f"{path}: required field {req!r} is missing — "
                           "an absent field is never an implicit answer")
        props = sch.get("properties", {})
        if sch.get("additionalProperties") is False:
            for k in inst:
                if k not in props:
                    extra = (" — the verdict is computed, never claimed"
                             if k == "final_verdict" else "")
                    out.append(f"{path}: unknown field {k!r}{extra}")
        for k, sub in props.items():
            if k in inst:
                _instance_errors(inst[k], sub, root, f"{path}/{k}", out)


# ==========================================================================
# git helpers (all read-only)
# ==========================================================================
def _git_show(commit, path):
    try:
        out = subprocess.run(["git", "-C", str(REPO), "show",
                              f"{commit}:{path}"], capture_output=True)
        return out.stdout if out.returncode == 0 else None
    except OSError:
        return None


def _commit_exists(sha):
    try:
        return subprocess.run(
            ["git", "-C", str(REPO), "cat-file", "-e", f"{sha}^{{commit}}"],
            capture_output=True).returncode == 0
    except OSError:
        return False


def _is_ancestor(a, b):
    try:
        return subprocess.run(
            ["git", "-C", str(REPO), "merge-base", "--is-ancestor", a, b],
            capture_output=True).returncode == 0
    except OSError:
        return False


def _path_kind(commit, path):
    """'blob', 'tree', or None, at the named commit."""
    try:
        out = subprocess.run(
            ["git", "-C", str(REPO), "cat-file", "-t", f"{commit}:{path}"],
            capture_output=True, text=True)
        return out.stdout.strip() if out.returncode == 0 else None
    except OSError:
        return None


def _sdr_exists(ident, commit):
    """An SDR-n citation must name a decision present in the decisions home
    at the named commit — matched at identifier boundaries, and scoped to
    MADE decisions: a mention in the pending queue grants nothing."""
    pat = r"(^|[^-A-Za-z0-9])" + re.escape(ident) + r"($|[^0-9a-z(])"
    try:
        return subprocess.run(
            ["git", "-C", str(REPO), "grep", "-qE", pat, commit, "--",
             DECISIONS_HOME,
             f":(exclude){DECISIONS_HOME}/PENDING-OWNER-DECISIONS.md"],
            capture_output=True).returncode == 0
    except OSError:
        return False


def _git_available():
    try:
        return subprocess.run(["git", "-C", str(REPO), "rev-parse",
                               "--git-dir"], capture_output=True).returncode == 0
    except OSError:
        return False


# ==========================================================================
# instrument readers
# ==========================================================================
def param_block_bytes(instrument_text: bytes):
    """§8's bytes: from the '## 8.' heading to the next '## ' heading."""
    txt = instrument_text.decode("utf-8", errors="replace")
    m = re.search(r"^## 8\..*$", txt, re.M)
    if not m:
        return None
    rest = txt[m.start():]
    nxt = re.search(r"^## (?!8\.)", rest[1:], re.M)
    return (rest if not nxt else rest[: nxt.start() + 1]).encode("utf-8")


def _norm_ws(s):
    return re.sub(r"\s+", " ", s).strip()


def instrument_version(instrument_text: bytes):
    m = re.search(r"^effective_version:\s*(v[0-9]+\.[0-9]+)",
                  instrument_text.decode("utf-8", errors="replace"), re.M)
    return m.group(1) if m else None


def launch_target_forms(pb_text):
    m = re.search(r"LAUNCH_TARGET:\s*>\n((?:[ \t]+\S[^\n]*\n)+)", pb_text)
    lt = _norm_ws(m.group(1)) if m else _norm_ws(pb_text)
    return (lt.rstrip("."), lt.split(". ")[0].rstrip("."))


def _yaml_list(pb_text, key):
    m = re.search(re.escape(key) + r":\s*\[([^\]]*)\]", pb_text)
    if not m:
        return None
    return [x.strip() for x in m.group(1).split(",") if x.strip()]


def e4_cases(pb_text):
    """The `E4_CASES` list, each case's quoted text, in the block's order.

    This is the one place the validator reads the instrument's own prose,
    and it is bounded and fail-closed by construction: it starts at the
    `E4_CASES` marker and takes numbered, double-quoted items only while
    their numbers run consecutively from 1, so the walk terminates at the
    first thing that is not the next case rather than wandering into the
    rest of §8. It returns None when it finds no case at all, and LA-10
    treats that as an error — never as "no cases to check". Reading the
    instrument, whose digest the record binds, is categorically different
    from parsing a generated report as authority: the bytes are pinned
    before the read, and a mismatch in count or text is an error either way.
    """
    m = re.search(r"`E4_CASES`", pb_text)
    if not m:
        return None
    out, expect = [], 1
    for item in re.finditer(r"^(\d+)\.[ \t]+\"(.*?)\"",
                            pb_text[m.start():], re.S | re.M):
        if int(item.group(1)) != expect:
            break
        out.append(_norm_ws(item.group(2)))
        expect += 1
    return out or None


# ==========================================================================
# validation
# ==========================================================================
def validate(record_path, schema_path=None, prior_path=None, _git=None):
    """Returns (errors, notes, computed) — computed carries the verdict and
    the trend figures. `_git` forces git checks on/off for fixtures."""
    errors, notes = [], []
    if _git is None:
        _git = _git_available()

    schema_path = Path(schema_path or DEFAULT_SCHEMA)
    try:
        schema = json.loads(Path(schema_path).read_text())
    except (OSError, ValueError) as exc:
        return ([f"LA-1: schema unreadable at {schema_path}: {exc}"], notes,
                {})
    audit = []
    _audit_schema(schema, "#", audit)
    if audit:
        return (["LA-1: " + a for a in audit], notes, {})

    try:
        raw = Path(record_path).read_text()
    except OSError as exc:
        return ([f"LA-1: record unreadable: {exc}"], notes, {})
    try:
        rec = json.loads(raw)
    except ValueError as exc:
        return ([f"LA-1: record is not valid JSON: {exc}"], notes, {})

    # ---- LA-1 schema conformance ----------------------------------------
    schema_errs = []
    _instance_errors(rec, schema, schema, "$", schema_errs)
    errors.extend("LA-1: " + e for e in schema_errs)
    if schema_errs:
        # Every later check indexes fields by name; running them over a
        # record that failed its shape produces noise, not findings.
        return (errors, notes, {})

    commit = rec["repository_commit"]
    rows = {q["question_id"]: q for q in rec["question_results"]}

    # ---- LA-4 roster ----------------------------------------------------
    seen = [q["question_id"] for q in rec["question_results"]]
    dupes = sorted({q for q in seen if seen.count(q) > 1})
    if dupes:
        errors.append("LA-4: question ID(s) answered more than once: "
                      + ", ".join(dupes) + " — a duplicate row would enter "
                      "the computed columns twice")
    missing = [q for q in ROSTER if q not in rows]
    if missing:
        errors.append("LA-4: question row(s) missing: " + ", ".join(missing)
                      + " — absence of a question is never a pass, and a "
                      "record short of the roster cannot support a gate "
                      "decision")
    extra = sorted(set(seen) - ROSTER_SET)
    if extra:
        errors.append("LA-4: row ID(s) outside the roster: "
                      + ", ".join(extra))

    # ---- LA-2 / LA-3 identity and binding -------------------------------
    pb_text = None
    if _git:
        if not _commit_exists(commit):
            errors.append(f"LA-2: named commit {commit} does not exist in "
                          "this repository — every citation is anchored to "
                          "it")
        else:
            blob = _git_show(commit, rec["instrument"]["path"])
            if blob is None:
                errors.append(
                    f"LA-2: instrument `{rec['instrument']['path']}` is not "
                    f"committed at {commit} — an administration against an "
                    "uncommitted instrument binds nothing")
            else:
                got = hashlib.sha256(blob).hexdigest()
                if got != rec["instrument"]["sha256"]:
                    errors.append(
                        "LA-2: instrument digest mismatch — the record "
                        f"quotes {rec['instrument']['sha256'][:12]}…, the "
                        f"committed instrument is {got[:12]}…")
                ver = instrument_version(blob)
                if ver and ver != rec["instrument"]["version"]:
                    errors.append(
                        f"LA-2: the record declares instrument version "
                        f"{rec['instrument']['version']} but the instrument "
                        f"committed at {commit} is {ver}")
                pb = param_block_bytes(blob)
                if pb is None:
                    errors.append("LA-2: the committed instrument has no §8 "
                                  "parameter block to digest")
                else:
                    gotp = hashlib.sha256(pb).hexdigest()
                    if gotp != rec["parameter_block_sha256"]:
                        errors.append(
                            "LA-2: parameter-block digest mismatch — the "
                            f"record quotes "
                            f"{rec['parameter_block_sha256'][:12]}…, §8 at "
                            f"the named commit is {gotp[:12]}…")
                    pb_text = pb.decode("utf-8", errors="replace")
                    forms = launch_target_forms(pb_text)
                    tgt = _norm_ws(rec["launch_target"]).rstrip(".")
                    if tgt not in forms:
                        errors.append(
                            f"LA-3: the record's launch target {tgt[:60]!r}… "
                            "is not the parameter block's LAUNCH_TARGET "
                            "(whitespace-normalized; its first sentence "
                            "suffices) — a fragment does not name the target "
                            "§8 binds")
                    for key, field in (("REQUIRED_WAVES", "required_waves"),
                                       ("DEFERRED_WAVES", "deferred_waves")):
                        want = _yaml_list(pb_text, key)
                        if want is not None and want != rec[field]:
                            errors.append(
                                f"LA-3: {field} is {rec[field]!r} but §8's "
                                f"{key} is {want!r} — the administration "
                                "must be bound to the parameters it names")
    else:
        notes.append("LA-2: git unavailable — identity, binding, E4 case "
                     "text and deferral-citation existence were NOT "
                     "verified; this record is not fully validated")

    # ---- LA-5 / LA-6 per-row discipline ---------------------------------
    for qid in ROSTER:
        row = rows.get(qid)
        if row is None:
            continue
        v, scope = row["verdict"], row["launch_scope"]
        if (v == SCOPED) != (scope == "deferred-wave-only"):
            errors.append(
                f"LA-5: {qid} carries verdict {v!r} beside launch_scope "
                f"{scope!r} — the scoped verdict and the scoped field are "
                "authored independently precisely so they must agree")
        if v == SCOPED and qid[0] not in "ABCD":
            errors.append(
                f"LA-5: {qid} carries the scoped verdict — lawful only in "
                "A–D (instrument §2/§4)")
        if v == MET and not row["evidence"]:
            errors.append(f"LA-6: {qid} is Met with no evidence entry — an "
                          "unsupported Met is recorded as Unknown")
        if v in (NOT_MET, SCOPED) and not row["counterexample"]:
            errors.append(f"LA-6: {qid} is {v!r} with no counterexample — a "
                          "Not met names the passage that fails or the "
                          "sweep, with its denominator, that shows absence")
        if v != UNKNOWN:
            for f in ("unknown_reason", "unknown_settlement"):
                if row[f] is not None:
                    errors.append(f"LA-6: {qid} is {v!r} but carries "
                                  f"{f} — the field belongs to Unknown")
        else:
            for f in ("unknown_reason", "unknown_settlement"):
                if not row[f] or _is_placeholder(row[f]):
                    errors.append(
                        f"LA-6: {qid} is Unknown with no {f} — §4 requires "
                        "every Unknown to carry what would settle it")
        if v not in (NOT_MET, SCOPED) and row["counterexample"] is not None:
            errors.append(f"LA-6: {qid} is {v!r} but carries a "
                          "counterexample — the field belongs to a Not met")
        if _is_placeholder(row["falsification_attempt"]):
            errors.append(f"LA-6: {qid}'s falsification_attempt asserts "
                          "emptiness — a verdict that survived no attempt "
                          "to break it is not credible (§2)")
        for i, ev in enumerate(row["evidence"]):
            if not commit.startswith(ev["commit"]) and \
                    not ev["commit"].startswith(commit):
                errors.append(
                    f"LA-6: {qid} evidence[{i}] is anchored to "
                    f"{ev['commit']} but the record names {commit} — "
                    "evidence quoted from any other version is void (§2)")

    # ---- LA-7 E1 rollup --------------------------------------------------
    if "E1" in rows and rows["E1"]["verdict"] == MET:
        bad = [q for q in E1_SUBROWS
               if q in rows and rows[q]["verdict"] != MET]
        if bad:
            errors.append("LA-7: E1 rolls up Met over non-Met sub-verdicts: "
                          + ", ".join(bad) + " — E1 is Met only when all "
                          "five are")

    # ---- LA-8 scoped disclosure -----------------------------------------
    scoped_rows = [q for q in ROSTER
                   if q in rows and rows[q]["verdict"] == SCOPED]
    findings_by_q = {}
    for f in rec["deferred_wave_findings"]:
        findings_by_q.setdefault(f["question_id"], []).append(f)
    if scoped_rows and not rec["deferred_wave_findings"]:
        errors.append(
            f"LA-8: {len(scoped_rows)} scoped row(s) and no deferred-wave "
            "finding — the record asserts a scoped defect exists and that "
            "none exists")
    for q in scoped_rows:
        fs = findings_by_q.get(q, [])
        if not fs:
            errors.append(f"LA-8: {q} is scoped but no deferred-wave "
                          "finding names it — the disclosure is the scoped "
                          "form's honesty, so it is checked, not trusted")
        for f in fs:
            if f["blocking_conditions_met"]:
                errors.append(
                    f"LA-8: {q}'s deferred-wave finding meets §4 blocking "
                    "condition(s) "
                    + ", ".join(f["blocking_conditions_met"])
                    + " — a defect meeting any of the five blocks the "
                    "verdict and cannot be rendered scoped")
    for f in rec["deferred_wave_findings"]:
        if f["wave"] not in rec["deferred_waves"]:
            errors.append(
                f"LA-8: a deferred-wave finding names wave {f['wave']!r}, "
                f"which is not in deferred_waves {rec['deferred_waves']!r}")

    # ---- LA-9 E3 ---------------------------------------------------------
    e3 = rec["e3"]
    reopen = e3["reopen_items"]
    if "E3" in rows:
        if rows["E3"]["verdict"] == MET:
            if not e3["concepts"] or not e3["trace_rows"]:
                errors.append(
                    "LA-9: E3 is Met without the credibility protocol's "
                    "concept enumeration and trace table — an empty reopen "
                    "list without the trace is Unknown, not Met (§3)")
            traced = {t["concept"] for t in e3["trace_rows"]}
            untraced = [c for c in e3["concepts"] if c not in traced]
            if untraced:
                errors.append(
                    "LA-9: E3 is Met with concept(s) traced to no shape "
                    "artifact: " + ", ".join(untraced))
            if reopen:
                errors.append(
                    f"LA-9: E3 is Met beside {len(reopen)} reopen item(s) — "
                    "§3's own rule is that a non-empty list makes 'ready' "
                    "false regardless of every other verdict")

    # ---- LA-10 E4 --------------------------------------------------------
    e4 = rec["e4"]
    results = e4["fixed_case_results"]
    idx = [r["case_index"] for r in results]
    if sorted(idx) != list(range(1, len(idx) + 1)):
        errors.append(f"LA-10: E4 case indices are {sorted(idx)!r} — the "
                      "fixed cases are answered once each, in the parameter "
                      "block's own numbering")
    if pb_text is not None:
        cases = e4_cases(pb_text)
        if cases is None:
            errors.append("LA-10: §8 at the named commit has no E4_CASES "
                          "block to bind the fixed cases to")
        else:
            if len(results) != len(cases):
                errors.append(
                    f"LA-10: {len(results)} E4 result(s) against "
                    f"{len(cases)} fixed case(s) in §8 — E4's comparability "
                    "across administrations is the whole point of fixing "
                    "them")
            for r in results:
                i = r["case_index"]
                if 1 <= i <= len(cases):
                    if _norm_ws(r["case_text"]) != cases[i - 1]:
                        errors.append(
                            f"LA-10: E4 case {i}'s text does not match §8's "
                            "own — a verdict rendered against a paraphrased "
                            "case is void (§2)")
    disagree = [r["case_index"] for r in results
                if r["routing_authority_says"] != "silent"
                and r["routing_authority_says"] != r["reviewer_classification"]]
    if disagree and "E4" in rows and rows["E4"]["verdict"] == MET:
        errors.append(
            "LA-10: E4 is Met while the reviewer and the routing authority "
            "disagree on case(s) " + ", ".join(str(i) for i in disagree)
            + " — disagreement with the project's routing is a fail")
    notes_blob = " ".join(rec["operationalization_notes"]).lower()
    for r in results:
        if r["routing_authority_says"] == "silent" and \
                r["needed_by_launch_target"]:
            if f"e4 case {r['case_index']}" not in notes_blob:
                errors.append(
                    f"LA-10: the routing authority is silent on E4 case "
                    f"{r['case_index']}, which the launch target needs "
                    "routed, and no operationalization note records it — §3 "
                    "makes that silence a finding in its own right")

    # ---- LA-11 deferrals -------------------------------------------------
    for d in rec["owner_deferrals"]:
        qid = d["question_id"]
        if qid not in ROSTER_SET:
            errors.append(f"LA-11: deferral names {qid!r}, which is not a "
                          "roster question")
        elif qid in NEVER_DEFERRABLE:
            errors.append(
                f"LA-11: a deferral is claimed against {qid} — §4 makes "
                "every conjunct but F2 non-deferrable, each carrying its "
                "own rationale for blocking")
        cite = d["decision_citation"].strip()
        if re.fullmatch(r"(?:P|D|B)-\d+[a-z]?(?:\([a-z]\))?", cite):
            errors.append(
                f"LA-11: {cite!r} grants no deferral — P-n names the queue "
                "of decisions *not* made, D-n a semantic-delta item, B-n "
                "review-finding numbering. A deferral is claimed by citing "
                "a made decision")
        elif re.fullmatch(r"SDR-\d+[a-z]?(?:\([a-z]\))?", cite):
            if _git and not _sdr_exists(cite, commit):
                errors.append(
                    f"LA-11: {cite} names no decision in {DECISIONS_HOME} "
                    f"at {commit}")
        elif "/" in cite:
            if _git:
                # A PREFIX strip, never `lstrip("./")` — that takes a
                # character SET and would eat the leading dot of
                # `.syzygy/…`, turning every governed path into a
                # non-existent one and every deferral citation into a
                # false error.
                rel = cite[2:] if cite.startswith("./") else cite
                kind = _path_kind(commit, rel)
                if kind is None:
                    errors.append(f"LA-11: the deferral path {cite!r} does "
                                  f"not exist at {commit}")
                elif kind != "blob":
                    errors.append(f"LA-11: the deferral path {cite!r} is a "
                                  f"{kind}, not a file — a directory grants "
                                  "nothing")
        else:
            errors.append(
                f"LA-11: {cite!r} is neither a repository path nor an SDR-n "
                "identifier — label wording is not a citation")
        if qid in rows and rows[qid]["verdict"] == MET:
            errors.append(
                f"LA-11: a deferral is claimed against {qid}, whose verdict "
                "is Met — a deferral defers a finding, and this row records "
                "none. A vacuous deferral would still convert a plain pass "
                "into READY-WITH-DEFERRALS")
        if _is_placeholder(d["bounded_reduction_plan"]):
            errors.append(
                f"LA-11: the deferral on {qid} carries no bounded reduction "
                "plan — §4 grants an F2 deferral only against one (maximum "
                "new meta-artifacts, artifacts to retire, stop condition)")

    # ---- LA-13 administration integrity ---------------------------------
    if rec["formal"]:
        if rec["administration_kind"] != "full":
            errors.append(
                "LA-13: a formal administration is declared with "
                f"administration_kind {rec['administration_kind']!r} — the "
                "gate decision requires a full administration at the named "
                "commit; regressions do not announce themselves (§2)")
        if not rec["reviewer"]["fresh_context"]:
            errors.append("LA-13: a formal administration is declared with "
                          "fresh_context false (§2)")

    # ---- LA-14 G1 --------------------------------------------------------
    if _is_placeholder(rec["g1"]["critic_answer"]):
        errors.append(
            "LA-14: G1's critic answer asserts emptiness — an administration "
            "missing G1 is incomplete and cannot support a gate decision, "
            "and a G1 that answers nothing is that absence wearing the "
            "shape of a presence")

    # ---- LA-15 trend anchoring ------------------------------------------
    prior = rec["prior_record"]
    if prior is not None:
        if prior["date"] > rec["date"]:
            errors.append(
                f"LA-15: the declared prior record is dated {prior['date']}, "
                f"after this administration's {rec['date']} — a later record "
                "is not a prior one")
        if _git:
            if not _commit_exists(prior["repository_commit"]):
                errors.append("LA-15: the prior record's commit "
                              f"{prior['repository_commit']} does not exist")
            elif _commit_exists(commit) and not _is_ancestor(
                    prior["repository_commit"], commit):
                errors.append(
                    f"LA-15: the prior record's commit "
                    f"{prior['repository_commit']} is not an ancestor of "
                    f"{commit} — a record from a divergent history is a "
                    "stale prior, and the trend delta computed against it "
                    "would be meaningless")
    if prior_path is not None:
        if prior is None:
            errors.append("LA-15: --prior was supplied but the record "
                          "declares prior_record: null")
        else:
            try:
                pj = json.loads(Path(prior_path).read_text())
            except (OSError, ValueError) as exc:
                errors.append(f"LA-15: --prior unreadable: {exc}")
                pj = None
            if pj is not None and \
                    pj.get("repository_commit") != prior["repository_commit"]:
                errors.append(
                    "LA-15: --prior names commit "
                    f"{pj.get('repository_commit')} but the record's "
                    f"prior_record names {prior['repository_commit']}")

    # ---- LA-16 pilot recurrence -----------------------------------------
    if rec["formal"] and prior is None:
        prc = rec["pilot_recurrence_check"]
        if not prc["performed"]:
            errors.append(
                "LA-16: this formal administration opens the trend log and "
                "records the §8 PILOT_RECURRENCE_CHECK as not performed — "
                "the pilot's own finding is the one recurrence the log "
                "cannot see")
        if _is_placeholder(prc["method"]):
            errors.append("LA-16: the pilot-recurrence check records no "
                          "method")

    # ---- LA-12 the §4 formula -------------------------------------------
    computed = _compute(rec, rows, prior_path)
    errors.extend(computed.pop("_errors"))
    return errors, notes, computed


def _compute(rec, rows, prior_path):
    """The §4 formula and the §6 trend figures, computed from the rows."""
    errs = []
    verdict_of = {q: rows[q]["verdict"] for q in rows}

    n_not_met = sum(1 for q in ROSTER
                    if verdict_of.get(q) == NOT_MET)
    n_scoped = sum(1 for q in ROSTER if verdict_of.get(q) == SCOPED)
    n_unknown = sum(1 for q in ROSTER if verdict_of.get(q) == UNKNOWN)
    n_deferred = len(rec["owner_deferrals"])
    n_reopened = len(rec["reopened_findings"])

    conjuncts = []

    def _c(name, ok, why):
        conjuncts.append((name, bool(ok), why))
        return bool(ok)

    e_all_met = all(verdict_of.get(q) == MET for q in E_ROWS)
    _c("every E question Met", e_all_met,
       ", ".join(f"{q}={verdict_of.get(q)!r}" for q in E_ROWS
                 if verdict_of.get(q) != MET) or "all Met")
    ad_blockers = [q for q in AD_ROWS if verdict_of.get(q) == NOT_MET]
    _c("no plain `Not met` in launch-scope A–D", not ad_blockers,
       ", ".join(ad_blockers) or "none")
    _c("F1 is Met or Unknown", verdict_of.get("F1") in (MET, UNKNOWN),
       f"F1={verdict_of.get('F1')!r}")
    _c("F3 is Met", verdict_of.get("F3") == MET,
       f"F3={verdict_of.get('F3')!r}")
    _c("F4 is Met", verdict_of.get("F4") == MET,
       f"F4={verdict_of.get('F4')!r}")
    # E3's reopen list is a conjunct of readiness in its own right (§3).
    _c("E3's reopen list is empty", not rec["e3"]["reopen_items"],
       f"{len(rec['e3']['reopen_items'])} item(s)")

    core = all(ok for _, ok, _ in conjuncts)

    f2 = verdict_of.get("F2")
    f2_deferrals = [d for d in rec["owner_deferrals"]
                    if d["question_id"] == "F2"]
    f2_met = f2 == MET
    f2_deferred = bool(f2_deferrals)

    if core and f2_met and n_deferred == 0:
        verdict = f"READY FOR {rec['launch_target']}"
        branch = "plain"
    elif core and f2_deferred and n_deferred > 0:
        verdict = "READY-WITH-DEFERRALS"
        branch = "deferrals"
    else:
        verdict = "NOT READY"
        branch = "blocked"

    # A pass that rests on any deferral is READY-WITH-DEFERRALS, never plain.
    if branch == "plain" and n_deferred:
        errs.append("LA-12: a plain READY verdict over a nonzero deferral "
                    "count is a contradiction (§4)")
    if branch == "deferrals" and not f2_met and not f2_deferred:
        errs.append("LA-12: READY-WITH-DEFERRALS substitutes exactly the F2 "
                    "limb, and no owner deferral names F2")
    if n_deferred and branch == "blocked" and core:
        errs.append("LA-12: deferrals are declared against a passing core "
                    "with no F2 deferral — the only deferrable limb is F2")

    new_findings = None
    if prior_path is not None:
        try:
            pj = json.loads(Path(prior_path).read_text())
            pv = {q["question_id"]: q["verdict"]
                  for q in pj.get("question_results", [])}
            newly_not_met = [q for q in ROSTER
                             if verdict_of.get(q) == NOT_MET
                             and pv.get(q) != NOT_MET]
            newly_scoped = [q for q in ROSTER
                            if verdict_of.get(q) == SCOPED
                            and pv.get(q) not in (NOT_MET, SCOPED)]
            new_findings = len(newly_not_met) + len(newly_scoped)
        except (OSError, ValueError):
            new_findings = None

    return {
        "_errors": errs,
        "verdict": verdict,
        "branch": branch,
        "conjuncts": conjuncts,
        "not_met": n_not_met,
        "scoped": n_scoped,
        "unknown": n_unknown,
        "deferred": n_deferred,
        "reopened": n_reopened,
        "new_findings": new_findings,
    }


def trend_row(rec, computed):
    nf = computed["new_findings"]
    return "| {} | {} | {} | {} | {} | {} | {} | {} | {} |".format(
        rec["date"], rec["repository_commit"][:7], computed["not_met"],
        computed["scoped"], computed["unknown"], computed["deferred"],
        computed["reopened"],
        "n/a (no prior record)" if nf is None else nf,
        computed["verdict"].replace("|", "/"))


# ==========================================================================
# selftest
# ==========================================================================
def _base_record(git_bound):
    """A minimal lawful record. When `git_bound`, identity fields are read
    from the instrument committed at HEAD so LA-2/LA-3/LA-10 have something
    real to check; otherwise they are synthetic and git checks are off."""
    row = {
        "question_id": None, "question_digest": "instrument-bound",
        "verdict": MET, "launch_scope": "in-launch-scope",
        "evidence": [{"path": "README.md", "commit": "0" * 40,
                      "locator": "line 1", "quote": "Syzygy"}],
        "counterexample": None, "unknown_reason": None,
        "unknown_settlement": None,
        "falsification_attempt": "tried to find a contradicting artifact",
    }
    commit = "0" * 40
    instrument = {"path": "launch-gate-pre-specifications.md",
                  "version": "v2.0", "sha256": "0" * 64}
    pbd = "0" * 64
    target = "Capability 1 — Project registration and honest shape visibility"
    req, dfr = ["A", "B"], ["C1", "C2", "D1", "D2"]
    cases = [(1, "case one"), (2, "case two")]
    if git_bound:
        commit = subprocess.run(["git", "-C", str(REPO), "rev-parse", "HEAD"],
                                capture_output=True, text=True).stdout.strip()
        blob = _git_show(commit, instrument["path"])
        instrument["sha256"] = hashlib.sha256(blob).hexdigest()
        instrument["version"] = instrument_version(blob)
        pb = param_block_bytes(blob)
        pbd = hashlib.sha256(pb).hexdigest()
        pbt = pb.decode("utf-8", errors="replace")
        target = launch_target_forms(pbt)[1]
        req = _yaml_list(pbt, "REQUIRED_WAVES") or req
        dfr = _yaml_list(pbt, "DEFERRED_WAVES") or dfr
        cases = list(enumerate(e4_cases(pbt) or [], start=1))
    rows = []
    for q in ROSTER:
        r = dict(row)
        r["question_id"] = q
        r["evidence"] = [dict(e, commit=commit) for e in row["evidence"]]
        rows.append(r)
    return {
        "schema_version": "2.0",
        "date": "2026-08-11",
        "administration_kind": "full",
        "formal": False,
        "instrument": instrument,
        "parameter_block_sha256": pbd,
        "repository_commit": commit,
        "launch_target": target,
        "required_waves": req,
        "deferred_waves": dfr,
        "reviewer": {"identity": "fixture", "model": "fixture",
                     "model_family": "fixture", "fresh_context": True,
                     "same_family_as_corpus_authors": False},
        "materials": {"included": ["the instrument"],
                      "withheld": ["prior administrations"],
                      "deviations": []},
        "operationalization_notes": [],
        "question_results": rows,
        "e3": {"concepts": ["registration"],
               "trace_rows": [{"concept": "registration",
                               "governing_artifact": "RFC-0002",
                               "note": "clause 4"}],
               "reopen_items": []},
        "e4": {"routing_authority": "SURFACE-CLAUSE-ROUTING-MATRIX.md",
               "fixed_case_results": [
                   {"case_index": i, "case_text": t,
                    "reviewer_classification": "shape",
                    "routing_authority_says": "shape",
                    "evidence": "matrix row", "needed_by_launch_target": False}
                   for i, t in cases]},
        "owner_deferrals": [],
        "deferred_wave_findings": [],
        "reopened_findings": [],
        "pilot_recurrence_check": {"performed": True,
                                   "method": "swept the retired phrases",
                                   "findings": []},
        "g1": {"critic_answer": "whether the gate itself is captured",
               "proposed_missing_questions": []},
        "falsification_summary": "attempted to break each Met",
        "prior_record": None,
    }


def _selftest():
    import tempfile
    n_cases = [0]
    failures = []
    git_on = _git_available()
    n_git_skipped = [0]

    def case(name, mutate, expect, git=False):
        """`expect` is a substring of a required error, or None to require a
        clean run. Every fixture mutates the base and asserts the check
        fires — a check that cannot fail is not a check."""
        n_cases[0] += 1
        if git and not git_on:
            n_git_skipped[0] += 1
            print(f"  SKIP  {name} (needs a git repository)")
            return
        rec = _base_record(git)
        mutate(rec)
        with tempfile.NamedTemporaryFile("w", suffix=".json",
                                         delete=False) as f:
            json.dump(rec, f)
            p = Path(f.name)
        try:
            errs, _notes, _c = validate(p, _git=git)
        finally:
            p.unlink()
        joined = " || ".join(errs)
        if expect is None:
            ok = not errs
            detail = joined[:200] if errs else ""
        else:
            ok = expect in joined
            detail = joined[:200] if not ok else ""
        print(f"  {'pass' if ok else 'FAIL'}  {name}")
        if not ok:
            failures.append((name, expect, detail))

    # --- the accepting direction -----------------------------------------
    case("a lawful record validates clean (no-git)", lambda r: None, None)
    case("a lawful record validates clean against the live instrument",
         lambda r: None, None, git=True)

    # --- LA-1 schema ------------------------------------------------------
    case("LA-1 unknown verdict word rejected",
         lambda r: r["question_results"][0].update(verdict="Partially met"),
         "outside the closed set")
    case("LA-1 a claimed final verdict is rejected, not compared",
         lambda r: r.update(final_verdict="READY"),
         "the verdict is computed, never claimed")
    case("LA-1 a missing required field is an error",
         lambda r: r.pop("g1"), "required field 'g1' is missing")
    case("LA-1 an unknown top-level field is an error",
         lambda r: r.update(gate_verdict="READY"), "unknown field")
    case("LA-1 a wrong type is an error",
         lambda r: r.update(formal="yes"), "expected boolean")
    case("LA-1 a malformed commit is an error",
         lambda r: r.update(repository_commit="HEAD"), "does not match")
    case("LA-1 an empty required string is an error",
         lambda r: r.update(falsification_summary=""),
         "shorter than the required")

    # --- LA-4 roster ------------------------------------------------------
    case("LA-4 a missing question is an error",
         lambda r: r["question_results"].pop(3), "question row(s) missing")
    case("LA-4 a duplicate question ID is an error",
         lambda r: r["question_results"].append(
             dict(r["question_results"][0])), "answered more than once")
    case("LA-4 an out-of-roster row is an error",
         lambda r: r["question_results"][0].update(question_id="A7"),
         "does not match")   # the pattern refuses it first

    # --- LA-2 / LA-3 identity --------------------------------------------
    case("LA-2 a wrong instrument digest is an error",
         lambda r: r["instrument"].update(sha256="a" * 64),
         "instrument digest mismatch", git=True)
    case("LA-2 a wrong parameter-block digest is an error",
         lambda r: r.update(parameter_block_sha256="b" * 64),
         "parameter-block digest mismatch", git=True)
    case("LA-2 a non-existent repository commit is an error",
         lambda r: r.update(repository_commit="d" * 40),
         "does not exist in this repository", git=True)
    case("LA-2 a wrong instrument version is an error",
         lambda r: r["instrument"].update(version="v9.9"),
         "but the instrument committed at", git=True)
    case("LA-3 a wrong launch target is an error",
         lambda r: r.update(launch_target="Capability 7 — something else"),
         "is not the parameter block's LAUNCH_TARGET", git=True)
    case("LA-3 wave lists must equal the parameter block's",
         lambda r: r.update(required_waves=["A"]),
         "the administration must be bound to the parameters it names",
         git=True)

    # --- LA-5 scope agreement --------------------------------------------
    case("LA-5 a scoped verdict without the scoped field is an error",
         lambda r: r["question_results"][0].update(
             verdict=SCOPED, counterexample="x"),
         "authored independently precisely so they must agree")
    case("LA-5 the scoped field without the scoped verdict is an error",
         lambda r: r["question_results"][0].update(
             launch_scope="deferred-wave-only"),
         "authored independently precisely so they must agree")
    case("LA-5 a scoped verdict outside A–D is an error",
         lambda r: (r["question_results"][ROSTER.index("F2")].update(
             verdict=SCOPED, launch_scope="deferred-wave-only",
             counterexample="x"),
             r["deferred_wave_findings"].append(
                 {"wave": "C1", "question_id": "F2", "defect": "d",
                  "blocking_conditions_met": []})),
         "lawful only in A–D")

    # --- LA-6 evidence discipline ----------------------------------------
    case("LA-6 Met with no evidence is an error",
         lambda r: r["question_results"][0].update(evidence=[]),
         "is Met with no evidence entry")
    case("LA-6 Not met with no counterexample is an error",
         lambda r: r["question_results"][0].update(verdict=NOT_MET),
         "with no counterexample")
    case("LA-6 Unknown with no settlement is an error",
         lambda r: r["question_results"][0].update(
             verdict=UNKNOWN, evidence=[], unknown_reason="no sweep"),
         "with no unknown_settlement")
    case("LA-6 a placeholder settlement asserts emptiness",
         lambda r: r["question_results"][0].update(
             verdict=UNKNOWN, evidence=[], unknown_reason="no sweep",
             unknown_settlement="none"),
         "with no unknown_settlement")
    case("LA-6 an Unknown field on a Met row is an error",
         lambda r: r["question_results"][0].update(
             unknown_reason="left over"), "the field belongs to Unknown")
    case("LA-6 a counterexample on a Met row is an error",
         lambda r: r["question_results"][0].update(counterexample="left over"),
         "the field belongs to a Not met")
    case("LA-6 a placeholder falsification attempt is an error",
         lambda r: r["question_results"][0].update(
             falsification_attempt="none"), "survived no attempt to break")
    case("LA-6 evidence anchored to another commit is an error",
         lambda r: r["question_results"][0]["evidence"][0].update(
             commit="e" * 40), "evidence quoted from any other version")

    # --- LA-7 E1 ----------------------------------------------------------
    case("LA-7 E1 cannot roll up Met over a non-Met sub-row",
         lambda r: r["question_results"][ROSTER.index("E1-home")].update(
             verdict=NOT_MET, counterexample="no home defined"),
         "rolls up Met over non-Met sub-verdicts")

    # --- LA-8 scoped disclosure ------------------------------------------
    case("LA-8 a scoped row with no deferred-wave finding is an error",
         lambda r: r["question_results"][0].update(
             verdict=SCOPED, launch_scope="deferred-wave-only",
             counterexample="x"),
         "and no deferred-wave finding")
    case("LA-8 a scoped row whose finding names another question is an error",
         lambda r: (r["question_results"][0].update(
             verdict=SCOPED, launch_scope="deferred-wave-only",
             counterexample="x"),
             r["deferred_wave_findings"].append(
                 {"wave": "C1", "question_id": "B2", "defect": "d",
                  "blocking_conditions_met": []})),
         "but no deferred-wave finding names it")
    case("LA-8 a finding meeting a blocking condition cannot be scoped",
         lambda r: (r["question_results"][0].update(
             verdict=SCOPED, launch_scope="deferred-wave-only",
             counterexample="x"),
             r["deferred_wave_findings"].append(
                 {"wave": "C1", "question_id": "A1", "defect": "d",
                  "blocking_conditions_met": ["on-default-route"]})),
         "blocks the verdict and cannot be rendered scoped")
    case("LA-8 a finding naming a non-deferred wave is an error",
         lambda r: r["deferred_wave_findings"].append(
             {"wave": "A", "question_id": "A1", "defect": "d",
              "blocking_conditions_met": []}),
         "which is not in deferred_waves")

    # --- LA-9 E3 ----------------------------------------------------------
    case("LA-9 E3 Met with a non-empty reopen list is an error",
         lambda r: r["e3"]["reopen_items"].append(
             {"item": "what a project is", "why": "undefined"}),
         "makes 'ready' false regardless")
    case("LA-9 E3 Met without the trace table is an error",
         lambda r: r["e3"].update(trace_rows=[]),
         "without the credibility protocol")
    case("LA-9 E3 Met with an untraced concept is an error",
         lambda r: r["e3"]["concepts"].append("evidence adapters"),
         "traced to no shape artifact")

    # --- LA-10 E4 ---------------------------------------------------------
    case("LA-10 a paraphrased E4 case is an error",
         lambda r: r["e4"]["fixed_case_results"][0].update(
             case_text="roughly the same thing"),
         "does not match §8's own", git=True)
    case("LA-10 a missing E4 case is an error",
         lambda r: r["e4"]["fixed_case_results"].pop(),
         "fixed case(s) in §8", git=True)
    case("LA-10 E4 Met over a routing disagreement is an error",
         lambda r: r["e4"]["fixed_case_results"][0].update(
             reviewer_classification="spec"),
         "disagreement with the project's routing is a fail")
    case("LA-10 unrecorded silence on a needed case is an error",
         lambda r: r["e4"]["fixed_case_results"][0].update(
             routing_authority_says="silent", needed_by_launch_target=True),
         "no operationalization note records it")
    case("LA-10 recorded silence on a needed case validates",
         lambda r: (r["e4"]["fixed_case_results"][0].update(
             routing_authority_says="silent", needed_by_launch_target=True),
             r["operationalization_notes"].append(
                 "E4 case 1: the routing authority is silent")),
         None)

    # --- LA-11 deferrals --------------------------------------------------
    def _defer(r, cite="SDR-9", qid="F2"):
        r["owner_deferrals"].append(
            {"question_id": qid, "decision_citation": cite,
             "bounded_reduction_plan": "at most 2 new meta-artifacts; "
                                       "retire 3; stop at the launch act"})
    case("LA-11 a P-n citation grants no deferral",
         lambda r: _defer(r, "P-34"), "grants no deferral")
    case("LA-11 a D-n citation grants no deferral",
         lambda r: _defer(r, "D-3"), "grants no deferral")
    case("LA-11 a B-n citation grants no deferral",
         lambda r: _defer(r, "B-2"), "grants no deferral")
    case("LA-11 label wording is not a citation",
         lambda r: _defer(r, "owner only"),
         "neither a repository path nor an SDR-n")
    case("LA-11 a non-existent deferral path is an error",
         lambda r: _defer(r, ".syzygy/governance/decisions/NOPE.md"),
         "does not exist at", git=True)
    case("LA-11 a directory grants nothing",
         lambda r: _defer(r, ".syzygy/governance/decisions"),
         "is a tree, not a file", git=True)
    case("LA-11 a deferral against a never-deferrable conjunct is an error",
         lambda r: _defer(r, "SDR-9", "F4"),
         "makes every conjunct but F2 non-deferrable")
    case("LA-11 a deferral with no bounded reduction plan is an error",
         lambda r: (_defer(r, "SDR-9"),
                    r["owner_deferrals"][0].update(
                        bounded_reduction_plan="tbd")),
         "carries no bounded reduction plan")

    # --- LA-12 the formula ------------------------------------------------
    def _expect_verdict(name, mutate, want, git=False):
        n_cases[0] += 1
        if git and not git_on:
            n_git_skipped[0] += 1
            print(f"  SKIP  {name} (needs a git repository)")
            return
        rec = _base_record(git)
        mutate(rec)
        with tempfile.NamedTemporaryFile("w", suffix=".json",
                                         delete=False) as f:
            json.dump(rec, f)
            p = Path(f.name)
        try:
            _e, _n, comp = validate(p, _git=git)
        finally:
            p.unlink()
        got = comp.get("verdict", "<none>")
        ok = got.startswith(want)
        print(f"  {'pass' if ok else 'FAIL'}  {name}")
        if not ok:
            failures.append((name, want, got))

    _expect_verdict("a clean record computes READY FOR the target",
                    lambda r: None, "READY FOR")
    _expect_verdict("one Not met in A–D computes NOT READY",
                    lambda r: r["question_results"][0].update(
                        verdict=NOT_MET, counterexample="x"), "NOT READY")
    _expect_verdict("a scoped row alone does not block",
                    lambda r: (r["question_results"][0].update(
                        verdict=SCOPED, launch_scope="deferred-wave-only",
                        counterexample="x"),
                        r["deferred_wave_findings"].append(
                            {"wave": "C1", "question_id": "A1",
                             "defect": "d", "blocking_conditions_met": []})),
                    "READY FOR")
    _expect_verdict("a Not met E row computes NOT READY",
                    lambda r: r["question_results"][ROSTER.index("E5")].update(
                        verdict=NOT_MET, counterexample="x"), "NOT READY")
    _expect_verdict("an Unknown F1 does not block",
                    lambda r: r["question_results"][ROSTER.index("F1")].update(
                        verdict=UNKNOWN, evidence=[],
                        unknown_reason="no trend yet",
                        unknown_settlement="a second administration"),
                    "READY FOR")
    _expect_verdict("a Not met F1 blocks",
                    lambda r: r["question_results"][ROSTER.index("F1")].update(
                        verdict=NOT_MET, counterexample="x"), "NOT READY")
    _expect_verdict("a Not met F3 blocks",
                    lambda r: r["question_results"][ROSTER.index("F3")].update(
                        verdict=NOT_MET, counterexample="x"), "NOT READY")
    _expect_verdict("a Not met F4 blocks",
                    lambda r: r["question_results"][ROSTER.index("F4")].update(
                        verdict=NOT_MET, counterexample="x"), "NOT READY")
    _expect_verdict("a Not met F2 with no deferral blocks",
                    lambda r: r["question_results"][ROSTER.index("F2")].update(
                        verdict=NOT_MET, counterexample="x"), "NOT READY")
    _expect_verdict(
        "a Not met F2 with an owner-cited deferral is READY-WITH-DEFERRALS",
        lambda r: (r["question_results"][ROSTER.index("F2")].update(
            verdict=NOT_MET, counterexample="x"), _defer(r)),
        "READY-WITH-DEFERRALS")
    _expect_verdict(
        "an Unknown F2 is deferrable on the same terms",
        lambda r: (r["question_results"][ROSTER.index("F2")].update(
            verdict=UNKNOWN, evidence=[], unknown_reason="no trend",
            unknown_settlement="two more administrations"), _defer(r)),
        "READY-WITH-DEFERRALS")
    _expect_verdict("a non-empty reopen list blocks every pass branch",
                    lambda r: r["e3"]["reopen_items"].append(
                        {"item": "x", "why": "y"}), "NOT READY")
    case("LA-11 a deferral beside a Met verdict is an error",
         lambda r: _defer(r), "a deferral defers a finding")
    # A pass carrying a deferral it does not rest on: §4 offers exactly two
    # pass words, and neither fits — plain READY forbids a nonzero deferral
    # count, and READY-WITH-DEFERRALS requires the F2 limb to be the
    # deferred one. The record is internally inconsistent, so the verdict
    # fails closed and the error names the inconsistency.
    _expect_verdict(
        "a deferral beside a Met F2 does not buy a plain READY",
        lambda r: (r["question_results"][ROSTER.index("F5")].update(
            verdict=NOT_MET, counterexample="same-family administration"),
            _defer(r, "SDR-9", "F5")),
        "NOT READY")
    case("LA-12 a deferral on a non-F2 limb beside a Not met F2 is an error",
         lambda r: (r["question_results"][ROSTER.index("F2")].update(
             verdict=NOT_MET, counterexample="x"),
             r["question_results"][ROSTER.index("F5")].update(
                 verdict=NOT_MET, counterexample="y"),
             _defer(r, "SDR-9", "F5")),
         "the only deferrable limb is F2")

    # --- LA-13 integrity --------------------------------------------------
    case("LA-13 a formal delta administration is an error",
         lambda r: r.update(formal=True, administration_kind="delta"),
         "the gate decision requires a full administration")
    case("LA-13 a formal administration without fresh context is an error",
         lambda r: (r.update(formal=True),
                    r["reviewer"].update(fresh_context=False)),
         "fresh_context false")

    # --- LA-14 G1 ---------------------------------------------------------
    case("LA-14 a placeholder G1 answer is an error",
         lambda r: r["g1"].update(critic_answer="none"),
         "G1's critic answer asserts emptiness")

    # --- LA-15 trend anchoring -------------------------------------------
    case("LA-15 a prior record dated after this one is an error",
         lambda r: r.update(prior_record={
             "path": "x.json", "repository_commit": "0" * 40,
             "date": "2026-12-01"}), "after this administration's")
    case("LA-15 a prior commit outside this history is a stale prior",
         lambda r: r.update(prior_record={
             "path": "x.json", "repository_commit": "f" * 40,
             "date": "2026-01-01"}), "does not exist", git=True)

    # --- LA-16 pilot recurrence ------------------------------------------
    case("LA-16 a formal opening administration must run the pilot check",
         lambda r: (r.update(formal=True),
                    r["pilot_recurrence_check"].update(performed=False)),
         "records the §8 PILOT_RECURRENCE_CHECK as not performed")

    # --- the schema-interpreter guard ------------------------------------
    n_cases[0] += 1
    audit = []
    _audit_schema({"type": "object", "propertyNames": {"type": "string"}},
                  "#", audit)
    ok = any("unsupported schema keyword" in a for a in audit)
    print(f"  {'pass' if ok else 'FAIL'}  the interpreter refuses a schema "
          "keyword it does not implement")
    if not ok:
        failures.append(("schema keyword audit", "unsupported", str(audit)))

    n_cases[0] += 1
    audit = []
    _audit_schema({"type": "object", "additionalProperties": True}, "#", audit)
    ok = any("additionalProperties: false" in a for a in audit)
    print(f"  {'pass' if ok else 'FAIL'}  the interpreter refuses "
          "`additionalProperties: true`")
    if not ok:
        failures.append(("additionalProperties audit", "false", str(audit)))

    n_cases[0] += 1
    audit = []
    _audit_schema(json.loads(DEFAULT_SCHEMA.read_text()), "#", audit)
    ok = not audit
    print(f"  {'pass' if ok else 'FAIL'}  the committed schema uses only "
          "implemented keywords")
    if not ok:
        failures.append(("committed schema audit", "clean", str(audit[:3])))

    # A second method, when it is available: the reference implementation.
    n_cases[0] += 1
    try:
        import jsonschema  # noqa: F401
        rec = _base_record(False)
        probe = jsonschema.Draft202012Validator(
            json.loads(DEFAULT_SCHEMA.read_text()))
        second = [e.message for e in probe.iter_errors(rec)]
        mine = []
        _instance_errors(rec, json.loads(DEFAULT_SCHEMA.read_text()),
                         json.loads(DEFAULT_SCHEMA.read_text()), "$", mine)
        ok = (not second) and (not mine)
        print(f"  {'pass' if ok else 'FAIL'}  the base record validates "
              "identically under the reference jsonschema implementation")
        if not ok:
            failures.append(("second method", "both clean",
                             f"reference={second[:2]} subset={mine[:2]}"))
    except ImportError:
        print("  note  jsonschema is not installed — the second-method "
              "cross-check did not run (it is never required: hosted CI "
              "installs no packages)")

    print(f"\n{n_cases[0]} fixtures, {len(failures)} failing — a check that "
          "cannot fail is not a check")
    if n_git_skipped[0]:
        print(f"WARNING: {n_git_skipped[0]} git-dependent fixture(s) were "
              "SKIPPED — this run is not evidence for them. Run inside a "
              "git repository.")
    for name, want, got in failures:
        print(f"  FAILED {name}\n    wanted: {want}\n    got: {got}")
    return 1 if failures else 0


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("record", nargs="?")
    ap.add_argument("--schema", default=None)
    ap.add_argument("--prior", default=None)
    ap.add_argument("--trend-row", action="store_true")
    ap.add_argument("--selftest", action="store_true")
    args = ap.parse_args(argv)

    if args.selftest:
        return _selftest()
    if not args.record:
        ap.error("a record path is required (or --selftest)")

    errors, notes, computed = validate(args.record, args.schema, args.prior)
    for n in notes:
        print(f"note: {n}")
    if computed:
        print(f"Computed gate verdict: {computed['verdict']}")
        for name, ok, why in computed["conjuncts"]:
            print(f"  [{'ok ' if ok else 'NO '}] {name} — {why}")
        print(f"  F2 limb: branch={computed['branch']}, "
              f"deferrals={computed['deferred']}")
        if args.trend_row:
            rec = json.loads(Path(args.record).read_text())
            print("\nTrend row (§6):")
            print(trend_row(rec, computed))
    if errors:
        print(f"\n{len(errors)} validation error(s):")
        for e in errors:
            print(f"  {e}")
        return 1
    print("\nrecord valid — the verdict above is computed from the rows")
    return 0


if __name__ == "__main__":
    sys.exit(main())
